---
output: pdf_document
---

\thispagestyle{empty}


\textbf{Background:} Multimorbidity, the presence of two or more long-term health conditions, is increasing in prevalence worldwide. This is due to increasing life expectancy although 30% of those aged 45-65 are also affected. Multimorbidity is associated with a number of negative outcomes including increased mortality, lower quality-of-life, and lower functional status. Unsurprisingly, it is also associated with greater use of health services. Little is known, however, about whether people with multimorbidity also receive more social care. The aim of the research was to assess the relationship between multimorbidity and social care, and the association of multimorbidity and social care on unplanned admission to hospital.

\textbf{Methods:} A retrospective population-based observational study using linked administrative health and social care records was conducted. All individuals over the age of 65 with a valid Community Health Index (CHI) number in Scotland during the financial years 2011/12 to 2015/16 were included. A proxy measurement of multimorbidity derived from prescribing data was used. Logistic regression models reporting Average Partial Effects (APEs) were employed to investigate associations between outcome and explanatory variables. Use of social care was assessed using the Scottish Social Care Survey (SCS). In order to assess its validity, all social care data from one local authority was obtained and analysed to assess the proportion of home care users likely to be captured by the SCS. 

\textbf{Results:} Over 1.1 million people were included in the cohort. 73% of participants were prescribed more than two repeat medicines. Multimorbidity was associated with receipt of social care. After adjustment for other variables, a 15% increased probability of receiving social care was observed for those in the highest multimorbidity group (receiving 9+ repeat medicines) compared to the lowest group (receiving 0-2 repeat medicines). Both multimorbidity and receipt of social care were associated with unplanned hospital admission after adjustment (9% increased probability of unplanned admission in the highest multimorbidity group, 7% increased probability for those that received social care). The SCS captured 60% of home care users representing up to 75% of all home care delivered in addition to all individuals receiving community alarm and telecare services.

\textbf{Conclusion:} This is one of the first studies to link health and social care data on a national scale. It showed an association between multimorbidity and use of social care. This finding is novel and indicates wider societal implications due to the increased prevalence of multimorbidity than has previously been described. Receipt of social care was also associated with increasing age, female sex, and lower socioeconomic position. Both multimorbidity and receipt of social care were associated with unplanned hospital admission. These findings have implications for policymakers interested in health and social care integration and the expected benefits of such reorganisation. 
