---
output: pdf_document
---

\thispagestyle{empty}


\begin{quotation}
Alienation is the precise and correctly applied word for describing the major social problem in Britain today. People feel alienated by society. In some intellectual circles it is treated almost as a new phenomenon. It has, however, been with us for years. What I believe to be true is that today it is more widespread, more pervasive than ever before. Let me right at the outset define what I mean by alienation. It is the cry of men who feel themselves the victim of blind economic forces beyond their control. It is the frustration of ordinary people excluded from the processes of decision making. The feeling of despair and hopelessness that pervades people who feel with justification that they have no real say in shaping or determining their own destinies. 

Many may not have rationalised it. May not even understand, may not be able to articulate it. But they feel it. It therefore conditions and colours their social attitudes.
\end(quotation)

James Reid. Rectorial Address delivered in the University of Glasgow. Friday, 28th April, 1972.