---
output: pdf_document
---

\chapter{Discussion}\label{ch:discussion}
\thispagestyle{empty}

This chapter discusses key findings from the thesis and places them in context. Given the broad nature of analyses, these are discussed in separate subsections. A section comparing findings to previous research is then presented before a section outlining the general strenghts and limitations of the thesis. The final section outlines recommendations for future research. 

\section{Key Findings in Context}\label{sec:key-finds}

This section is split into five subsections detailing key findings from analyses and the PhD research in general: a) Patterns in receipt of social care, b) Patterns in unplanned hospital admissions, c) Health and social care interaction, d) social care data, and e) Linked admnistrative data research.

\subsection{Patterns in receipt of social care}\label{subsec:mm-sc-kfinds}

This analyses of patterns of social care use in Scotland is novel given its linkage of health and social care resources and has a number of findings and implications. The descriptive statistics in section \ref{sec:res1-sc} and the first set of models presented in chapter \ref{ch:res2} investigated the factors associated with receipt of social care. One important aspect was to identify if a relationship between multimorbidity and social care existed as this had been identified as a gap in existing empirical knowledge. The results indicate that such a relationship does indeed exist and that the effect of this relationship grows as the severity of multimorbidity (measured by grouped repeat medicine counts) increases. The change in probability of receiving social care for those in the highest multimorbidity group (prescribed nine-or-more repeat medicines) compared to those in the lowest group (prescribed 0-2 medicines) is approximately 15%. This change is approximately 6.5% and 3% for the 6-8 and 3-5 repeat medicine groups respectively.  

These results are broadly consistent across models applied to differing financial years of data. Subset 2 (including individuals from nine local authorities with a linkage rate of 92%-95.9%) showed slightly lower values of partial effects for all age, sex, and multimorbidity groups group compared to subset 1. This may be due to the larger size of subset 2 which included approximately 77,000 more individuals overall and less uncertainty for the lower numbers in smaller groups. Nevertheless, overall patterns are similar across both subsets. 

The use of partial (or marginal) effects to interpret logistic regression models allows comparison of effect sizes across variables and models after adjustment for all included independent variables [@RN563]. In both subsets of data, models across all years showed the partial effect of being in the highest multimorbid group compared to the lowest was of similar magnitude to that of being aged 80-84 compared to being aged 65-69. In other words, after adjustment for age, sex, and sociodemographic variables, being in the highest multimorbidity group is equivalent to being 10-15 years older than the baseline age group. 

The identification of the relationship between multimorbidity and social care use is important both for health clinicians and policy makers. High levels of multimorbidity have the potential to indicate need for social care which should be a consideration when assessing this patient group. Given the increasing prevelance of multimorbidty and the reduction in funding for social care (discussed in chapter \ref{ch:lit-review}), urgent consideration of social care provision and funding by policy-makers is warranted. 

This argument has further support given that social care receipt also has, unsurprisingly, an association with age. Given demographic trends, the demand for social care services is only likely to increase. Indeed, the only other measurements with higher magnitude of partial effects than the highest multimorbidity group were those related to higher age groups, particularly the three age groups in which those over 85 belonged to: 85-89, 90-94, and 95 plus. The magnitude of effects for these groups were particularly high indicating that, after adjustment for other model variables, being in these age groups was associated with approximately 29%, 42%, and 47% increased probability of receiving social care compared to those in the 65-69 age group respectively (again slightly lower effects were seen in subset 2). Standard errors were higher, and their associated 95% confidence intervals wider, for the two highest age groups than seen for other variables reflecting the lower overall numbers in these groups. Nevertheless, social care receipt has a strong relationship in age groups over 85 years which is likely to reflect higher levels of frailty. 

Unexpectedly, the effect of socioeconomic position, as measured by SIMD decile of residence, is negligible after adjusting for other variables in the models of both subsets. This is an important finding and suggests that the higher rates of social care receipt for those living in lower SIMD deciles shown in tables \ref{tab:res2-chars1516} and \ref{tab:res2-2-chars1516} are attenuated after adjustment for age, multimorbidity, sex, and local authority of residence. The likely reason for this can be discerned from the pattern shown in figure \ref{fig:results1-heatmap-1}. This shows that, apart from those in the highest multimorbidity group (9+ repeat medicines), the rate of care received in each group is more evenly spread across deprivation deciles - resulting in the small partial effect of SIMD decile in the models. This effect can be more easily discerend in figure \ref{fig:results1-heatmap-2} where rates of care \emph{within} each age/sex group are visualised.  The higher rates of social care receipt in lower SIMD deciles, therefore, are driven by those (particularly females) in the highest multimorbidity group. This would suggest care is concentrated on those with highest need reflecting the arguments of "intensification" discussed in chapter \ref{ch:lit-review}.  

Tables \ref{tab:res2-chars1516} and \ref{tab:res2-2-chars1516} both show higher percentages of females receiving social care compared to males whilst figure \ref{fig:results1-sc-demos} shows this pattern is consistent across all ages. Depsite this, the APE for being female is relatively small in models - 4% and 3.2% increased probability in subset 1 and 2 respectively. This suggests multimorbidity status attenuates some, but not all, of the higher rates of social care received by females - a pattern also visible in figure \ref{fig:results1-heatmap-2}. The remaining gap between sexes in social care receipt could potentially be explained by two reasons. Firstly, females may be more likely to live alone and therefore have greater need for social care in older age. Secondly, females may be more likely to provide, and less likely to receive, informal care to or from a partner. Whilst a variable for living arrangements is available in the SCS, there are high levels of missing data meaning it could not be accurately included in models. 

A final finding from the analysis on social care receipt is that variation between local authorities is also present. The differences in the probability of receiving social care of 6.2% between Na h-Eileanan Siar and South Ayshire in subset 2 (table \ref{tab:res2-model2-APE}) is comparable to the difference in probability between the second-highest multimorbidity group (6-8 repeat medicines) and it's reference group (0-2 repeat medicines). However, it must be noted this was the largest inter-council difference in subset 2 (the corresponding difference in subset 1 was 5%) and many APEs for councils were broadly similar. Given the variation in linkage rates across local authority areas, and the lack of multi-level modelling in analysis, robust conclusions about the effect of local authority of residence and receipt of social care cannot be drawn at present. Nevertheless, this is an important finding that warrants further exploration. 

In summary, the analysis indicates that social care receipt is driven primarily by age and multimorbidity stauts. These factors attenuate a large proportion of the greater rates of care delivered to females and those living in more deprived areas. The findings support the "intensification" description of social care provision and add evidence that care is concentrated on those with high levels of multimorbidity living in the poorest areas. Increasing prevelence of multimorbidity and the increasing proportion of the population in older age groups are likely to increase demand for social care services significantly.    

\subsection{Patterns in unplanned hospital admissions}\label{sec:dsicuss-adm}

Descriptive statistics (section \ref{sec:res1-adm}) and models (section \ref{sec:res3-usc}) analysing factors associated with unplanned hospital admission in the six months after the end of each financial year reveal a relationship between a number of variables and admission. Average Partial Effects increase with severity of multimorbidity, a pattern easily discernable from the change in colour by multimorbidity group in figure \ref{fig:results1-heatmap-3} and the more naive visualisation in figure \ref{fig:results1-adm-demos}. 

The magnitude of multimorbidity APEs, as for all variables, are much lower than seen in social care models. For example, compared with being in the lowest multimorbidity group (0-2 repeat medicines), being in the highest multimorbidity group (9 plus repeat medicines) increases the probability of unplanned admission by between 8% and 9% across models (compared to 13% - 15% increased probability of receiving social care). Nevertheless, multimorbidity is shown to have an important relationship with unplanned hospital admission.  

The increase in probability of admission of 6%-7% and 7%-8% for those that received social care or had previously used any form of unscheduled care (unplanned admission, A & E, GP OOH, NHS24 or Ambulance service) respectively, indicates those with hospital admissions are more likely to be high users of all health and social care services. This is an important finding indicating a cohort of very sick individuals interact with services in both health and social care services and may account for a large proportion of service demand. Given the strong effect of multimorbidity status on receipt of social care, the potential that social care acts as a proxy for multimorbidity in the unplanned hospital admission model is possible. (*Is it??*)

One area where this may not be the case is for those that live in care homes although findings varied across models. The direction of effect on unplanned hospital admission for those living in a care home changes from 2014/15 onwards. In models fitted to earlier financial years, living in a care home has a small (<1%) increase in probablity of unplanned admission. Models fitted to data from 2014/15 and 2015/16 show a decreased probability of admission of almost 2%. It is difficult to ascertain the cause of this change. The obvious temporal difference could have a number of explanations including policy change or, more likely, change in data collection methods.     

An increase in APEs is also seen through age groups although this is not a linear pattern. The oldest age group (95 plus) has a lower APE point estimate than the next oldest (90-94) although larger confidence intervals, which overlap in all years, are present suggesting there is little difference in APE over the age of 90.   

The models fitted to identify factors associated with unplanned hospital admissions had a poor fit as measured by McFadden's pseudo $R^{2}$ in all years and, therefore, caution is required when interpreting results. There is the possibility that other unmeasured factors could improve model fit. It also notable that the magnitude of APEs are considerably smaller than seen for social care models suggesting more complex factors associated with unplanned hospital admission may exist.  

In summary, age and multimorbidity are shown to have relationships with unplanned hospital admission. Those that receive social care and those that have used unscheduled health care services in the financial year prior to the exposure period also have a higher probability of unplanned hospital admission. Caution is required in interpreting these results given the poorer fit to data found with logisitc regression models. 

\subsection{Health and social care interaction}

Although two different models were conducted in analysis, comparison of results (and descriptive statistics) presents cogent arguments to the debate on the interaction between health and social care services. 

Perhaps the most important comparison is between the heatmaps showing the overall distribution of social care and unplanned hospital admission presented in figures \ref{fig:results1-heatmap-1} and \ref{fig:results1-heatmap-3}. As previously discussed the former highlights the "intensification" of social care services focussed on, particularly female, highly multimorbid groups of lower socioeconomic position. Comparison to the latter figure shows the distribution of unplanned admission to hospital, whilst also affecting predominantely low SIMD decile residents with high multimorbidity, has a wider distribution affecting more males and younger age groups. If, as the policy of health and socal care integration explicitly aims to achieve, social care provision is to reduce the number of unplanned hospital admissions, then the distribution of the receipt of care will need to broaden to groups other than those over 80.

There is, however, no evidence from the analysis that suggests receipt of social care can have a preventative effect on unplanned hospital admission. Indeed, those receiving social care have a higher probability of an unplanned admission than those that do not. Nevertheless, as discussed in section \ref{sec:dsicuss-adm}, "intensification" of services in recent years means that those with anything below the highest of needs are unlikely to receive social care. The effect of social care receipt could have on their outcomes remains a matter of conjecture. 

A further argument regarding health and social care interaction raised in the analysis related to preventative measures. Given the strong effects increasing multimorbidity has on receipt of both social care and unplanned hospital admission (visible in heatmaps and model results), the results of analysis add weight to the many calls for a focus on preventative public health measures to attenuate the need for services. Compared to the highest multimorbidity group, those receiving 6-8 or 3-5 repeat medicines had much lower rates of unplanned admission and social care use. Those, even at older ages, in the lowest multimorbidity group (receiving 0-2 repeat medicines) had very little use of either service. Preventative measures that reduce the proportion of the population in the highest multimorbidity group could have a big impact on demand for health and social care services. 

Relevant to both these arguments is discussion regarding primary care (e.g. WHO [-@RN599] and section \ref{subsec:litrv-mm-context}) where universal coverage, despite issues with the inverse care law, is generally regarded as the most appropriate way of improving access to service in order to deliver effective (and preventative) care for those with multimorbidity. Whether universal coverage of social care could have the same effect, and potentially mitigate the need for unplanned admission, is a matter of debate. However, the current means-and-needs tested model of social care provision in the UK is unlikely to help in this regard. With a link established between multimorbidity and social care use, identifying interactions between primary care and social care use is now an important potential research avenue requiring exploration. 


\subsection{Social care data}\label{sec:disc-sc-data}

The first aim of the PhD was to identify what Scottish social care data sources existed that could be linked to health data and asses their suitablility for research purposes. The SCS was identified as the most suitable source to assess social care outcomes at a \emph{national} level however, as with many forms of routine adminsitrative data, a number of limitations exist. The cross sectoral nature of some parts of the data collection limits the types of statistical analysis that can be applied with it. For example, if start and end dates of social care receipt were recorded at the individual level, time-to-event (survival) analysis could provide more robust findings on factors influencing receipt of social care. As such simplar methods, such as logisitc regression used in chapter \ref{ch:res2}, are more suited to the nature of the SCS. 

As discussed in more detail in chapter \ref{ch:renfrew}, however, there remains the issue of how well the \emph{home} care aspect of the SCS represents the total number of individuals receiving care in any financial year. Using presence or not in the SCS as a binary measure of receipt of social care, such as analyses in chapter \ref{ch:res2}, misclassifies some individuals by indicating they have not received care when in fact they would have done. As the discussion in chapter \ref{ch:renfrew} identifies, the ~60% of individuals that the SCS would have identified as receiving home care in the Renfrewshire area is likely to be an underestimate of the coverage of total social care for the models in chapter \ref{ch:res2} for two reasons. 

Firstly, the analysis in chapter \ref{ch:renfrew} could not account for mortality and therefore overall proportions include those that died in the financial year prior to the census date. These individuals were omitted from analysis in chapter \ref{ch:res2}, therefore a higher proportion of individuals that survived to the census date will be classified correctly. 

Secondly, the Renfrewshire analysis did not estimate the proportion of individuals who received home care \emph{and} telecare services. The extended data collection procedures applied to the SCS from financial year 2013/14 onwards meant details of community alarm and telecare users \emph{at any time in the financial year} were included in the SCS. An unknown proportion of these individuals, already included in the SCS, will also receive home care services at times not overlapping the census week. In chapter \ref{ch:renfrew} such individuals will have been counted as having being "missed" by the census when in fact, due to their receipt of a telecare or alarm service, were indeed captured.

Despite these limitations, the main finding of chapter \ref{ch:renfrew} indicates a potential minimum coverage of the SCS. A further finding suggests that individuals who receive social care and whose data are not collected by the SCS are more likely to be recipients of shorter-term care. These individuals are often in receipt of "Reablement" type services which are intentionally short lived. A flag for reablement was not available for the data linked for the PhD but will be collected as part of future SCS collections. Coupled with the likely underestimate of coverage discussed above, this finding suggests using the SCS as an indicator of receipt of social care is likely to capture a large majority of individuals receiving long-term care.

Whilst this is welcoming, further issues remain with use of the SCS that limit the types of analyses that can be conducted. The lack of consistent recording of a CHI number in SCS collection meant probabilistic matching methods based on name, date-of-birth, gender, and postcode were required in order to create indexes that could then link the SCS to health records (more fully explained in section \ref{sec:linkage}). Whilst this matching process produced good overall results (91% match rate nationally) and rates were consistent across age, gender, and deprivation groups, there was large variation in match rates at the local authority level (76.7% - 98.5% for 31 of 32 local authorities). In effect, these variations introduce missing data not at random and make comparison in rates of care across local authorities problematic. Analysis in chapter \ref{ch:res2} attempted to overcome this problem by creating two subsets of data including local authorities with above average match rates. Whilst this allows some appraisal of variations in receipt of care at the local authority level, gaining a national picture remains elusive.  

Although these issues are important, and analyses must take account of the limitations, the SCS remains an important resource in international terms. Social care data for research is recognised to be of poorer quality than health related data and often very difficult to link health records in many countries [@RN406]. Where linkages have been able to be made, inclusion of measures of home-based social care are less frequent [@RN610]. This means that, regardless of the limitations described above, the linked health and social care dataset created for analysis in this PhD is an important resource for research as it addresses both of these issues. 

One final (incidental) finding that can be inferred from the analysis of social care data in the Renfrewshire area, reported in chapter \ref{ch:renfrew}, adds to the debate surrounding eligibility and allocation of social care. As argued by Sharkey (2006, p.10) (quoted at the beginning of section \ref{subsubsec:eligibility-uk}), eligibility criteria can be seen as a form of rationing where "..."need" is equated with ``resources available"." Figure \ref{fig:ren-hc-counts} shows that, whilst year-to-year variations are discernable, the weekly variation in the number of individuals receiving home care is remarkably stable. The deduction that a finite number of home care spaces are available at any given time, and that termination of one individual's care must occur before another's can start, seems credible. Whilst this may have been intuitively known previously, figure \ref{fig:ren-hc-counts} provides some empirical evidence to the debate. 

\subsection{Linked administrative data research}\label{sec:disc-admin-data}

As cross-sectoral data linkages remain a novel methodology for PhD research, a number of issues relevant to the process of obtaining a linked dataset are worthy of discussion to inform future funders or researchers who wish to comission or undertake similar projects.

The most important of these is time. Whilst all doctoral research is time-consuming, and often runs past deadline, projects utilising data from multiple public bodies have extra barriers than more traditional forms of research. Whilst the approvals process can seem overly robust at first glance, it is an essential step in ensuring research of this nature is conducted in a safe and legal manner. Nurturing a good relationship with a designated research co-ordinator from eDRIS can greatly assist in production of a research proposal that will meet the requirements of the PBPP with few revisions in a timely manner. 

The controlled data service offered by UBDC, although adding an extra layer of approval for the project, was invaluable through the support of a designated member of staff to assist in negotiating the complicated approvals process. This is particularly important for PhD students where previous experience in applying to RAC or PBPP is unlikely. Support of this nature should be considered for all PhD researchers taking on new projects. 

In this PhD, one of the main aims was to identify what sort of social care existed that could be linked to health sources. Although the SCS was quickly identified as the most suitable source, the decision as to whether indexing to the NRS population spine would take place, enabling linkage to health data, could only be taken by the Scottish Government. This decision was around about the beginning of the 2nd year of study (Sept 2016) with actual indexing taking place approximately one year after that. This had obvious repercussions for other aspects of project management including data sharing agreements and extraction of cohort data (a full timeline is shown in figure \ref{fig:timeline}). Future PhD projects would benefit from using previously used data sources or data for which access has already been negotiated. 

The delay in obtaining linkable SCS data highlights a major temporal obstacle for those carrying out similar types of research; namely the lack of control over the completion of key project factors. Where data sources come from public sector organisations, even those with excellent infrastructure to enable data sharing such as ISD, extraction of project data is one of many tasks the organisation's analysts will be dealing with. Where university lawyers are required to write and amend data sharing agreements, the project contract is one of many important documents on their desk. Where data is being shared from a local authority, unexpected events, such as an unanticipated general election, mean staff designated to prepare and extract study data are unable to do so because of other, essential, work demands. The higher number of organisations involved, the more delays occur. The cumulative effect makes project management very difficult as the completion date for any given task is an unknown quantity.

Further constraints to data linkage projects involve developing the skill of undertaking analysis within a safe haven environment. Little training or documentation is available to assist in gaining these skills and much of it is done by trial-and-error. Efficiency of the national safe haven could be improved if stakeholders (e.g. eDRIS, Research Institutes, and the Scottish Government) could arrange some simple training for future users. This could include subjects such as: access procedures, software, maintanence, and statistical disclosure control (SDC) - reducing unnecessary queries and data output requests not conforming to SDC requirements.

A further efficiency saving in terms of SDC could be achieved through improved practices in the appraisal of work by PhD students and their supervisors. Over 600 items were cleared through SDC procedures for the purposes of this thesis with the potential for more relating to associated academic publications. This number could be greatly reduced if, where remote access to the safe haven has been granted, an agreed format for sharing and commenting on draft findings was agreed from \emph{within} the safe haven (e.g. Markdown reports in html with comments in a separate MS Word document).

A final point, particularly for those conducting analysis, is to be aware of the software being used and the way in which it is updated within the safe haven. Analysis for this thesis was predominantly conducted using the R language for statistical programming. This software is exceptionally versatile and benefits from constant development via an open source community of programmers. However, without internet access, updating packages to preferred versions can be cumbersome. This process has changed, and greatly improved, over the lifetime of the PhD with a total CRAN mirror now being updated on an almost monthly basis but researchers need to be aware of the limitations of this approach. 

\section{Comparisons to Previous Research}\label{sec:discuss-comparisons}

This is the first study, to the author's knowledge, that has aimed specifically identified relationships between multimorbidity and requirement for social care. Much previous research has focussed on the the effect social care has as an explanatory variable on other outcomes - usually in a secondary care setting. Whilst multimorbidity may also be included as an explanatory variable in these studies e.g. [@RN30], the relationship between them is not explored. The positive, increasing effect of multimorbidity status on both social care receipt and unplanned hospital admission found in this thesis (and by Codelius \emph{et al.}[-@RN30]) indicates that it is a common driver for the use of both services.

The lack of use of home-based care as an independent variable in research focussing on secondary care outcomes had been indentified as a gap in knowledge by Spiers \emph{et al.} [-@RN610] in their systematic review. Analysis in chapter \ref{ch:res2} addresses this ommision. Contrary to the overall findings of the systematic review, the analysis suggests social care has no prevantative effect on unplanned admission, indeed receipt of social care carried an increased probability of admission. This is likely due to the requirement for a high level of need to be deemed eligible to receive social care. 

This finding supports those of other studies that linked social care data at the individual level [@RN183; @RN30]. Both these studies also found those in receipt of social care utilised a higher proportion of secondary care services. The large, population nature of the cohort in this thesis addresses the limitations of these studies which each included data from only four local authority areas and could potentially be unrepresentative of wider populations. The models fitted to each financial year of data in section \ref{sec:res3-usc} included an average of 864,500 (to the nearest 500) individuals from 31 of Scotland's 32 local authorities. As such, the data is nationally representative across all sociodemographic factors. 

Models in section \ref{sec:res3-usc} indicated, for later years, that those living in a care home had a lower probability of an unplanned hospital admission than those that were not. As mentioned in previous discussion, this finding should be treated with some caution. The reliability of the care home flag in CHI datasets has been shown to lack sensitivity and as such may underestimate the number of care home residents [@RN642]. Furthermore, there is no obvious reason why the direction of the effect on unplanned admission changes from 2014/15 onwards. Overall numbers in the cohort with a postive value for the care home flag decreased by over 8000 from 2011/12 to 2015/16 (table \ref{tab:results1-cohorttab}). This is a gradual decrease, however, and unlikely to be the cause of effect change

Both Spiers \emph{et al.} [-@RN610] and Bardsley \emph{et al.} [-@RN183] reported findings regarding the effect of being resident in a care homes on secondary care outcomes. The former found, by pooling results from studies using aggregate data, that an increase in the availability of care home beds was associated with fewer admissions, delayed discharges, and reduced length of stay. The latter found that those resident in a care home were less likely to have a hospital admission than those receiving intense levels of home care. Spiers \emph{et al.} [-@RN610] rightly identify the challenges of heterogeneity in data applied to the methodological approach they employed. Of their 12 included studies, only three were used to pool estimates on outcomes related to care homes. Bardsley \emph{et al.} [-@RN183], and analysis in section \ref{sec:res3-usc}, omitted individuals who died in the year prior to the study period of interest. Those in the final year of life are likely to have at least one hospital admission [@RN645] which could affect results of models where these individuals are omitted. As such, conclusions can not be accurately drawn regarding the effect of care home admission on secondary care outcomes.    

The use of a count of prescriptions as a proxy measurement of multimorbidity (as discussed in section \ref{subsec:mm-measures}) has been previously shown to be a good predictor of health care use [@RN228; @RN247; @RN78]. The use of grouped repeat medicine counts in chapter \ref{ch:res2} show marked changes in partial effects in the receipt of social care and unplanned admission across groups. This adds to the argument that a count of medicines can act as useful proxy where disease data is unavailable. 

Of course, the specific method of how prescriptions are counted could have an effect on these measures. Comparing the way in which medicines were counted in chapter \ref{ch:res2} to other research is difficult given differing exposure periods and cohort profiles used. However, figures \ref{fig:results1-meds-hist}, \ref{fig:results1-meds-age-grp}, and \ref{fig:results1-meds-simd-age} show distribution patterns broadly similar to figure 1 in Brilleman & Salisbury [-@RN247] and figure 1 in Guthrie \emph{et al.} [-@RN274] (when focussing on the 65 plus age group only). Another study, using a similar age profile and aiming to identify inappropriate prescribing from PIS data [@RN580], found a higher percentage of individuals with at least one prescription compared to results in table \ref{tab:results1-cohorttab} (94% v 89%), This is likely due to the two-year exposure period employed in the former study compared to (repeated) one-year exposure in this thesis. 


\section{Strengths and Limitations}

\subsection{Strengths}

The study is the first, in a UK setting, to link health data to social care records at a national level. The main strength of the research carried out is in the size of dataset created to answer the designated research questions. By creating a non-selective study population of all individuals over the age of 65 in Scotland during the study period (~1.1 million individuals), and linking their data from a number of different health and social care sources, a comprehensive description of this group has been provided. It is the first study to specifically investigate the relationship between multimorbidity and social care use. As such, the findings offer important insights for clinicians and policy-makers alike. 

The use of individual-level data is another important strength of this research. Previous studies investigating the interaction between health and social care services relied on aggregate statistics, often at local authority or higher level, to estimate outcomes. These studies are unable to account for individual characteristics that can have an important role in such interactions. 

The handful of previous cross-sectoral studies that have used individual-level data have been limited to using social care data from no more than a handful of local authorities at a time e.g. [@RN183; @RN30]. The large resource in this PhD, despite the limitations discussed in the next section and section \ref{sec:disc-sc-data}, mean concerns of sampling bias or external validity seen in these studies is eradicated. 

The quality of the dataset created for the thesis is demonstrated in its inclusion as part of the Administrative Data Research Centre for Scotland's successful phase 2 funding bid to the Economic and Social Research Council. The bid outlined areas where, pending required approvals, future research utilising this data could be conducted. *Can I mention post-doc post here?* 

Whilst the proportion of individuals receiving home care that were captured by the SCS was previously unknown, analysis in chapter \ref{ch:renfrew} has provided the first estimation of this value. Despite limitations in the data available from Renfrewshire council, the finding that those missing from the census are likely to be in receipt of short-term care is important. This validation of the SCS enables results of analysis with the linked dataset to be interpreted with more confidence than if it had not been done.

In terms of analysis, the use of Average Partial Effects as a means of interpreting logisitic regression models allows comparison of effect magnitudes between variables within models and across models. These comparisons offer valuable insights that could not be considered by reporting odds-ratios or variable probabilities alone. This method also enables coefficients for interaction effects to be included in predicting probabilities (and variable marginal effects) without incurring the problems (discussed in section \ref{sec:methods-stats}) of misinterpreting the coefficients themselves. 

\subsection{Limitations}\label{sec:discuss-limits}

A number of limitations to this research have already been discussed, particularly in sections \ref{sec:disc-sc-data} and \ref{sec:discuss-comparisons}. However, there remain other general limitations which will be further explored in this section. 

All analyses carried out in this thesis are conducted using observational data. As such, only associations between variables are found and no causal inferences can be made from results. It is also possible, as with all observational research, that unobserved confounding variables could have an important role to play in outcome effects.

Of these, the lack of a measure of living arrangements is most regrettable. Those living alone are more likely to require formal social care, indeed officially reported statistics from the SCS suggets 55% of those over 65 receiving home care live alone [@RN487]. Inclusion of this measurement in statistical models could, therefore, potentially account for further variation in receipt of care. This figure, however, is based on approximately 60% of SCS respondents, data was missing for the remainder. Coupled with added attrition in the linkage process and the likelihood of missingness not at random (i.e. some local authorities not returning this data at all), this available measurement was not of sufficient quality to confidently include in analyses. Potential solutions would involve expanding the data linkage to include UK census data which includes a measure of home circumstances. This would, however, involve significant ammendments to approved permissions granted by PBPP.  

The research presented in the thesis exclusively focusses on \emph{formal} social care provided by the state. The provision of \emph{informal} social care (by family and friends) has a major role to play in debates regarding health and social care service use. By its very nature, informal care remains particularly difficult to capture in administrative records (again the UK census offers potential). As such inclusion in projects such as this PhD remain elusive. This is also true of privately arranged social care. The ability of more affluent individuals to purchase social care has potential to influence unplanned hospital care although administrative records of such care are unlikely to exist.

Another unobserved measure that could be useful in this area is one of \emph{frailty} or \emph{need}. The associations found between multimorbidity and service use in analyses could potentially be explained, partially at least, by individual levels of frailty or need. The defintion of frailty remains a matter of some debate [@RN646] (much in the same way as the definition of multimorbidity discussed in chapter \ref{ch:lit-review}), and the terms are often used synonomously. No standardised measure of frailty is collected in administrative data at a national level in Scotland. A measure of need, The indicator of Relative Need (ioRN2) score [@RN647], was developed in Scotland would be a very useful measurement in this regard. However, the lack of mandatory assessment means few local authorities return data with an ioRN2 score to the SCS. Early analysis of PhD data showed over 90% of records had a missing value for ioRN2 score and the variable was therefore dropped from analysis. 

Further limitations include the statistical analysis employed to find results. The delivery of data for the linkage project was completed in February 2018. Given the size of each dataset (e.g. social care, demographics, prescriptions etc.) and the complexity of wrangling data into a suitable format, the time available for data exploration and analysis was limited within the life-time of the PhD. Results presented provide an excellent description of the linked data and identify important variables and relationships regarding stated research questions. This analysis provides an excellent platform for further understanding. It did not, however, take advantage of the longitudinal nature of the data. Despite social care data being of a cross sectional nature, repeated measures for individuals are available. Start and stop dates for all episodes of unscheduled care are avaialable. Time-to-event analysis is but one potential method that could be applied to this data to provide more robust results, particularly regarding unplanned admission where logistic regression models had a poor fit to the data. 

A final limitation includes the possibility of important literature from chapter \ref{ch:lit-review}. The nature of the thesis, and the broad topics relevant to the aims and objectives, meant a systematic review of literature was not appropriate. Much of the debate and information relevant to the research, particularly in the case of social care, was to be found in grey literature that would not be identified by traditional academic database searching. For other subjects where academic literature was more important, e.g. multimorbidity and administrative data linkage, emphasis was place on systematic reviews and publications by independent organisations with expertise in the specific area to idenitify the most relevant literature. Nevertheless, literature relevant to overall arguments may have been missed. 

\section{Recommendations for future research}

As discussed in section \ref{sec:discuss-limits}, creation of the linked data consumed a large part of the time available during the PhD. The results presented in chapters \ref{ch:results-1} and \ref{ch:res2}, whilst providing a detailed description of the data, offer only a glimpse of potential lines of enquiry that could be followed using this resource. The most pertinent of these, related to the aims and objectives of the thesis, are discussd in this section. 

The first, examination of longitudinal changes in social care and unscheduled care use, has already been discussed in section \ref{sec:discuss-limits}. The size and depth of data available provides an excellent platform to provide a more in-depth understanding of the provision and factors influencing receipt of social care as well as its interactions with unscheduled health care. Future analyses should take advantage of the depth of infomation available.  

Better understanding may also be found by further utilising the granularity of social care data. A simple yes/no measure of receipt was used in analysis in chapters \ref{ch:results-1} and \ref{ch:res2}. Variables measuring intensity of home care (via a value of weekly hours of home care received) and whether an individual received a community alarm or other telecare service are available. Both these measures may have interesting effects on outcomes that remain unexplored. 

There remains more data within the unscheduled care data mart that has not been investigated. Unplanned hospital admission was studied for this project but data on attendance at A & E, GP out-of-hours service, NHS24 use, and ambulance service use is also available. Myriad insights relating to the interaction of these services with each other, demographics, multimorbidity, and social care are possible.

Another important factor, related to both social care and USC, is mortality. Death records are also included in the linkage cohort. There has been a recent increase in interest regarding outcomes for individuals in their last months of life e.g. hospital use [@RN648;@RN645], out-of-hours primary care [@RN649], and medication use [@RN650]. All of these topics could be investigated further with the PhD dataset which would also have the benefit of a larger cohort and a wider set of explanatory variables to choose from than seen in any one of these studies, including aspects relating to social care which are absent from all.   

Whilst variations in the linkage rate at the local authority level of SCS records to the CHI population spine is problematic, results found in this thesis warrant further investigation. The difference in probabilities of receiving care across council areas with similar linkage rates raises questions regarding eligibility criteria and the inverse care law. Understanding whether these variations are due to data quality, natural variation, or unfairness in the system is of vital importantance to policy debates.

Future research should also employ other methods of measuring multimorbidity. Alternative measures such as a count of the number of chapters of the BNF (as a proxy for body systems) an individual has prescriptions from, or modelling the count of repeat medicines as a continuous, rather than categorical, variable may add to the understanding of relationships with outcomes. Where research only involves indiviudals who used USC, disease data in the form of ICD-10 codes is available. These can be used to created comorbidity scores from indices described in section \ref{subsec:mm-measures} and could be cross-referenced with medicine counts. 

Finally, linkage to other data sources should be considered. UK census data contains variables that could greatly add to understanding in the areas covered by this thesis e.g. by identifying individuals who lived alone or had an informal carer. The potential to link to primary care data should also be explored. Interactions between primary care and social care use remain largely unknown in a research context. This is an impotant area to explore given the findings from this thesis of the relatioship between multimorbidity and social care. Data from GP surgeries offers a more comprehensive ability to measure multimorbidity than is available from current data collections and could greatly improve understanding in this field. 




