---
output: pdf_document
---

\begin{appendices}

\chapter*{Appendix A. Main linkage PBPP approval}\label{app:a}
\thispagestyle{empty}
\includepdf[pages={-}]{data/assets/pbpp.pdf}

\chapter*{Appendix B}\label{app:b}
\thispagestyle{empty}

\begin{longtable}{@{}lr@{}}
\caption{Medicines not included in total counts}
\label{append-tab-1} \\
\toprule
Medicine Name & BNF subsection \\* \midrule
\endfirsthead
%
\multicolumn{2}{c}%
{{\bfseries continued from previous page}} \\
\toprule
Medicine Name & BNF subsection \\* \midrule
\endhead
%
\bottomrule
\endfoot
%
\endlastfoot
%
GLUCAGON & 06.01.04 \\
OILS FOR THE EAR & 12.01.03 \\
CHLORHEXIDINE GLUCONATE & 12.03.04 \\
ENTERAL NUTRITION & 09.04.02 \\
DOCUSATE SODIUM & 12.01.03 \\
EMOLLIENTS & 13.01.01 \\
SUNSCREEN & 13.08.01 \\
POVIDONE IODINE & 13.11.04 \\
OXYGEN CYLINDERS & 03.06.00 \\
MULTIVITAMINS & 09.06.07 \\
\begin{tabular}[c]{@{}l@{}}LIDOCAINE HYDROCHLORIDE \\ WITH CHLORHEXIDINE GLUCONATE\end{tabular} & 15.02.01 \\
WATER FOR INJECTIONS & 09.02.02 \\
HEPARINOID & 13.14.00 \\
DICLOFENAC & 13.08.01 \\
PROFLAVINE HEMISULFATE & 13.10.05 \\
RALOXIFENE HYDROCHLORIDE & 06.04.01 \\
\begin{tabular}[c]{@{}l@{}}COMPOUND TOPICAL PREPARATIONS \\ WITH LIDOCAINE\end{tabular} & 15.02.01 \\
FOODS FOR SPECIAL DIETS & 09.04.01 \\
\begin{tabular}[c]{@{}l@{}}COMPOUND PREPARATIONS WITH \\ SALICYLIC ACID\end{tabular} & 13.07.00 \\
KETOROLAC TROMETAMOL & 11.08.02 \\
BENZOCAINE & 12.03.03 \\
FOODS FOR SPECIAL DIETS & 09.04.02 \\
MAGNESIUM SULFATE & 13.10.05 \\
HYDROGEN PEROXIDE & 13.11.06 \\
FLUOROURACIL & 13.08.01 \\
UREA HYDROGEN PEROXIDE & 12.01.03 \\
METHYLPREDNISOLONE & 10.01.02 \\
GLUCOSE & 09.02.02 \\
CHLORHEXIDINE GLUCONATE & 13.11.02 \\
LIDOCAINE & 15.02.01 \\
\begin{tabular}[c]{@{}l@{}}AMYLMETACRESOL AND \\ DICHLOROBENZYL ALCOHOL\end{tabular} & 12.03.03 \\
CETYLPYRIDINIUM CHLORIDE & 12.03.03 \\
SALICYLIC ACID & 13.07.00 \\
HEXETIDINE & 12.03.04 \\
GLUTEN FREE BISCUITS & 09.04.01 \\
GLUTEN FREE MIXES & 09.04.01 \\
GLUTEN FREE BREAD & 09.04.01 \\
GLUCOSE & 06.01.04 \\
\begin{tabular}[c]{@{}l@{}}CETRIMIDE AND \\ CHLORHEXIDINE GLUCONATE\end{tabular} & 13.10.05 \\
ORCIPRENALINE SULFATE & 03.01.01 \\
BOWEL CLEANSING SOLUTIONS & 01.06.05 \\
IMIQUIMOD & 13.07.00 \\
ENTERAL NUTRITION & 09.04.01 \\
OXYGEN CYLINDERS WITH SET & 03.06.00 \\
COMPOUND HERBAL PREPARATIONS & 09.12.00 \\
ZINC OXIDE & 13.13.01 \\
ALUMINIUM DIHYDROXYALLANTOINATE & 13.12.00 \\
\begin{tabular}[c]{@{}l@{}}CETYLPYRIDINIUM CHLORIDE WITH \\ CHLOROCRESOL AND\\ LIDOCAINE HYDROCHLORIDE\end{tabular} & 12.03.04 \\
GLUTEN FREE/LOW PROTEIN BISCUITS & 09.04.01 \\
LOW PROTEIN BISCUITS & 09.04.01 \\
GLUTEN FREE PASTA & 09.04.01 \\
GLUTEN FREE/WHEAT FREE BISCUITS & 09.04.01 \\
GLUTEN FREE/WHEAT FREE BREAD & 09.04.01 \\
HYOSCINE HYDROBROMIDE & 15.01.03 \\
MIDAZOLAM & 15.01.04 \\
POTASSIUM PERMANGANATE & 13.11.06 \\
POVIDONE IODINE & 13.10.05 \\
GLUTEN FREE/WHEAT FREE MIXES & 09.04.01 \\
FOODS FOR SPECIAL DIETS & 09.11.04 \\
ALUMINIUM CHLORIDE HEXAHYDRATE & 13.12.00 \\
GLUTEN FREE/WHEAT FREE PASTA & 09.04.01 \\
SODIUM CHLORIDE & 09.02.02 \\
HELICOBACTER PYLORI TEST & 01.03.00 \\
GLUCOSAMINE SULFATE & 09.12.00 \\
LIDOCAINE HYDROCHLORIDE & 15.02.01 \\
TRIAMCINOLONE ACETONIDE & 10.01.02 \\
GLUTEN FREE GRAINS/FLOURS & 09.04.01 \\
HYDROGEN PEROXIDE & 13.10.05 \\
APRACLONIDINE & 11.08.02 \\
PODOPHYLLUM & 13.07.00 \\
AMINO ACID SUPPLEMENTS & 09.04.01 \\
LIDOCAINE HYDROCHLORIDE & 12.03.03 \\
IODINE & 13.11.04 \\
CAMOUFLAGERS & 13.08.02 \\
COVERING AGENTS & 13.08.02 \\
CETOMACROGOL & 13.01.01 \\
GLUTARALDEHYDE & 13.07.00 \\
MENTHOL WITH EUCALYPTUS & 03.08.00 \\
CALCIUM FOLINATE & 08.01.00 \\
SILVER NITRATE & 13.07.00 \\
DEQUALINIUM CHLORIDE & 12.03.03 \\
GLUTEN FREE/WHEAT FREE GRAINS/FLOURS & 09.04.01 \\
CATHETER PATENCY SOLUTIONS & 07.04.04 \\
NEPAFENAC & 11.08.02 \\
HEXYLRESORCINOL & 12.03.03 \\
CETRIMIDE & 13.10.05 \\
PREDNISOLONE & 10.01.02 \\
\begin{tabular}[c]{@{}l@{}}CETRIMIDE AND CHLORHEXIDINE \\ GLUCONATE\end{tabular} & 13.11.02 \\
\begin{tabular}[c]{@{}l@{}}SODIUM PICOSULFATE AND \\ MAGNESIUM CITRATE\end{tabular} & 01.06.05 \\
SODIUM BICARBONATE & 09.02.02 \\
LOW PROTEIN MIXES & 09.04.01 \\
BENZALKONIUM CHLORIDE & 12.03.03 \\
BENZOIN & 03.08.00 \\
CEFPODOXIME & 05.01.02 \\
ALCOHOL & 13.11.01 \\
\begin{tabular}[c]{@{}l@{}}CHLORHEXIDINE IN \\ ISOPROPYL ALCOHOL\end{tabular} & 13.11.02 \\
TETRACAINE & 11.07.00 \\
SYRUP & 09.11.01 \\
COMBINED FOOD PREPARATION & 09.11.04 \\
CHLORHEXIDINE IN METHYLATED SPIRIT & 13.11.02 \\
HYDROCORTISONE ACETATE & 10.01.02 \\
GLUCOSE & 09.04.01 \\
DIBROMOPROPAMIDINE ISETIONATE & 13.10.05 \\
ISOPROPYL ALCOHOL & 13.11.01 \\
INOSINE ACEDOBEN DIMEPRANOL & 05.03.02 \\
EPINEPHRINE & 02.07.03 \\
CHLORHEXIDINE GLUCONATE & 13.10.05 \\
THYMOL & 12.03.04 \\
DICLOFENAC & 11.08.02 \\
FLUORESCEIN SODIUM & 11.08.02 \\
LOW PROTEIN BREAD & 09.04.01 \\
TETRACAINE & 15.02.01 \\
ALFENTANIL & 15.01.04 \\
FOODS FOR SPECIAL DIETS & 09.09.00 \\
FOODS & 09.04.02 \\
\begin{tabular}[c]{@{}l@{}}CHLOROBUTANOL AND \\ CHLORHEXIDINE GLUCONATE\end{tabular} & 12.03.04 \\
FORMALDEHYDE & 13.07.00 \\
GLYCOPYRRONIUM BROMIDE & 15.01.03 \\
\begin{tabular}[c]{@{}l@{}}CHLORHEXIDINE DIGLUCONATE AND\\  TETRACAINE HYDROCHLORIDE\end{tabular} & 12.03.03 \\
OXYBUPROCAINE HYDROCHLORIDE & 11.07.00 \\
SOLVENT ETHER & 13.11.01 \\
PHLEUM PRATENSE & 03.04.02 \\
BENZOCAINE & 13.02.03 \\
TALC PURIFIED & 13.02.03 \\
PHOSPHATES (RECTAL) & 01.06.05 \\
DIAZOXIDE & 06.01.04 \\
BUPIVACAINE HYDROCHLORIDE & 15.02.01 \\
\begin{tabular}[c]{@{}l@{}}LIDOCAINE HYDROCHLORIDE WITH\\  CHLORHEXIDINE GLUCONATE\end{tabular} & 12.03.03 \\
TENECTEPLASE & 02.10.02 \\
LOW PROTEIN PASTA & 09.04.01 \\
LIDOCAINE WITH EPINEPHRINE & 15.02.01 \\
\begin{tabular}[c]{@{}l@{}}AMYLMETACRESOL AND DICHLOROBENZYL \\ ALCOHOL WITH ASCORBIC ACID\end{tabular} & 12.03.03 \\
GENTIAN & 09.07.00 \\
PHENOL & 13.11.05 \\
ETYNODIOL DIACETATE & 07.03.02 \\
GLUTEN FREE/LOW PROTEIN PASTA & 09.04.01 \\
SODIUM BENZOATE & 12.03.04 \\
MISCELLANEOUS HERBALS & 09.12.00 \\
WITCH HAZEL & 13.11.06 \\
LOW PROTEIN CEREALS & 09.04.01 \\
GLUTEN FREE COOKING AIDS & 09.04.01 \\
SODIUM HYPOCHLORITE & 13.11.04 \\
CHLORHEXIDINE IN ISOPROPYL ALCOHOL & 13.11.01 \\
LACTASE & 09.11.02 \\
KETOROLAC TROMETAMOL & 15.01.04 \\
KETAMINE & 15.01.01 \\
MAGNESIUM CITRATE & 01.06.05 \\
CHLOROXYLENOL & 13.11.05 \\
LIDOCAINE WITH AMINOACRIDINE & 12.03.03 \\
ATROPINE SULFATE & 15.01.03 \\
PROXYMETACAINE HYDROCHLORIDE & 11.07.00 \\
ENTERAL NUTRITION & 09.09.00 \\
FLUOROURACIL WITH SALICYLIC ACID & 13.08.01 \\
LIDOCAINE AND TETRACAINE & 15.02.01 \\
PARAFFIN HARD & 13.01.01 \\
FENTANYL & 15.01.04 \\
FOODS FOR SPECIAL DIETS & 09.11.01 \\
MESNA & 08.01.00 \\
MOXIFLOXACIN & 11.08.02 \\
DECOGESTANT DROPS & 03.08.00 \\
BROMFENAC & 11.08.02 \\
HYDROGEN PEROXIDE & 12.03.04 \\
SODIUM CHLORIDE & 07.04.04 \\
LOW PROTEIN FOODS & 09.04.01 \\
LOW PROTEIN GRAINS/FLOURS & 09.04.01 \\
PHENOL WITH CHLORHEXIDINE GLUCONATE & 13.10.05 \\
INGENOL MEBUTATE & 13.08.01 \\
GLUTEN FREE CEREALS & 09.04.01 \\
INTRAVENOUS NUTRITION SUPPLEMENTS & 09.03.00 \\
VITAMINS C AND D3 WITH FOLIC ACID & 09.06.07 \\
DINOPROSTONE & 07.01.01 \\
CRANBERRY & 09.12.00 \\
ALUMINIUM CHLORIDE & 13.12.00 \\
POTASSIUM CHLORIDE & 09.02.02 \\
BRIMONIDINE TARTRATE & 13.06.03 \\
\begin{tabular}[c]{@{}l@{}}BENZOYL PEROXIDE WITH \\ POTASSIUM HYDROXYQUINOLINE\end{tabular} & 13.11.02 \\
ULIPRISTAL & 06.04.01 \\
ALKYL SULFATE & 13.11.03 \\
PRILOCAINE HYDROCHLORIDE & 15.02.01 \\
RACECADOTRIL & 01.04.03 \\
DAPOXETINE & 07.04.06 \\
CARBOMER & 11.08.03 \\
POVIDONE IODINE & 11.08.02 \\
ERGOMETRINE MALEATE & 07.01.01 \\
LOW PROTEIN COOKING AIDS & 09.04.01 \\
PIRFENIDONE & 03.11.01 \\
\begin{tabular}[c]{@{}l@{}}LIDOCAINE HYDROCHLORIDE \\ WITH FLUORESCEIN SODIUM\end{tabular} & 11.07.00 \\
FLEXIBLE COLLODION & 13.10.05 \\
BECAPLERMIN & 13.11.07 \\
MIVACURIUM CHLORIDE & 15.01.05 \\
NORETHISTERONE ENANTHATE & 07.03.02 \\
SOAP & 13.11.03 \\
LANOLIN & 13.01.01 \\
FOODS & 09.04.01 \\
CIPROFLOXACIN WITH DEXAMETHASONE & 12.01.02 \\
INSULIN DEGLUDEC AND LIRAGLUTIDE & 06.01.02 \\
\begin{tabular}[c]{@{}l@{}}LIDOCAINE HYDROCHLORIDE WITH \\ CETYLPYRIDIUM CHLORIDE\end{tabular} & 15.02.01 \\
MULTIVITAMINS & 09.10.00 \\* \bottomrule
\end{longtable}


\chapter*{Appendix C. Renfrewshire pilot. Ethical approval}\label{app:g}
\thispagestyle{empty}
\includepdf[pages={-}]{data/assets/renf-ethics.pdf}

\end{appendices}

\chapter*{Appendix D. Supplementary tables and plots}
\thispagestyle{empty}

\begin{landscape}
\begin{longtable}[c]{@{}lrrrrrrr@{}}
\caption{Social care models. Subset 1. Model results}
\label{append-tab-2} \\
\toprule
Term & estimate & std.error & statistic & p.value & odds\_ratio & conf\_int\_low & conf\_int\_high \\* \midrule
\endfirsthead
%
\multicolumn{8}{c}%
{{\bfseries Table \thetable\ continued from previous page}} \\
\toprule
Term & estimate & std.error & statistic & p.value & odds\_ratio & conf\_int\_low & conf\_int\_high \\* \midrule
\endhead
%
\bottomrule
\endfoot
%
\endlastfoot
%
(Intercept) & -4.251 & 0.103 & -41.165 & \textless{}0.001 & 0.014 & 0.012 & 0.017 \\
Female & 0.152 & 0.045 & 3.355 & 0.001 & 1.164 & 1.065 & 1.272 \\
Age: 70-74 & 0.674 & 0.111 & 6.07 & \textless{}0.001 & 1.962 & 1.578 & 2.439 \\
Age: 75-79 & 1.544 & 0.104 & 14.86 & \textless{}0.001 & 4.684 & 3.821 & 5.742 \\
Age: 80-84 & 2.539 & 0.099 & 25.528 & \textless{}0.001 & 12.666 & 10.422 & 15.391 \\
Age: 85-89 & 3.56 & 0.102 & 35.006 & \textless{}0.001 & 35.174 & 28.817 & 42.934 \\
Age: 90-94 & 4.464 & 0.118 & 37.937 & \textless{}0.001 & 86.818 & 68.937 & 109.337 \\
Age: 95 Plus & 4.836 & 0.18 & 26.931 & \textless{}0.001 & 125.909 & 88.556 & 179.019 \\
SIMD Decile: & -0.135 & 0.012 & -11.03 & \textless{}0.001 & 0.874 & 0.853 & 0.895 \\
Meds: 3-5 & 0.898 & 0.11 & 8.173 & \textless{}0.001 & 2.455 & 1.979 & 3.044 \\
Meds: 6-8 & 1.515 & 0.106 & 14.265 & \textless{}0.001 & 4.549 & 3.695 & 5.602 \\
Meds: 9+ & 2.599 & 0.099 & 26.205 & \textless{}0.001 & 13.452 & 11.075 & 16.338 \\
councilAngus & -0.01 & 0.078 & -0.13 & 0.897 & 0.99 & 0.849 & 1.154 \\
councilEasy Ayrshire & -0.187 & 0.06 & -3.122 & 0.002 & 0.83 & 0.738 & 0.933 \\
councilInverclyde & -0.176 & 0.061 & -2.895 & 0.004 & 0.838 & 0.744 & 0.945 \\
councilSouth Lanarkshire & -0.425 & 0.053 & -8.046 & \textless{}0.001 & 0.654 & 0.589 & 0.725 \\
councilStirling & -0.221 & 0.08 & -2.75 & 0.006 & 0.802 & 0.685 & 0.939 \\
counciNorth Ayrshire & -0.415 & 0.058 & -7.202 & \textless{}0.001 & 0.661 & 0.59 & 0.739 \\
councilDumfries and Galloway & -0.811 & 0.072 & -11.201 & \textless{}0.001 & 0.444 & 0.386 & 0.512 \\
councilArgyll and Bute & -0.538 & 0.09 & -5.953 & \textless{}0.001 & 0.584 & 0.489 & 0.697 \\
Female:age\_grp70-74 & 0.243 & 0.06 & 4.058 & \textless{}0.001 & 1.275 & 1.134 & 1.433 \\
Female:age\_grp75-79 & 0.386 & 0.056 & 6.912 & \textless{}0.001 & 1.472 & 1.319 & 1.642 \\
Female:age\_grp80-84 & 0.467 & 0.054 & 8.622 & \textless{}0.001 & 1.595 & 1.435 & 1.774 \\
Female:age\_grp85-89 & 0.453 & 0.057 & 7.975 & \textless{}0.001 & 1.572 & 1.407 & 1.757 \\
Female:age\_grp90-94 & 0.164 & 0.07 & 2.356 & 0.018 & 1.179 & 1.028 & 1.351 \\
Female:age\_grp95 Plus & -0.027 & 0.122 & -0.224 & 0.823 & 0.973 & 0.766 & 1.236 \\
SIMD Decile: :meds\_grp3-5 & 0.045 & 0.012 & 3.86 & \textless{}0.001 & 1.046 & 1.022 & 1.069 \\
SIMD Decile: :meds\_grp6-8 & 0.058 & 0.011 & 5.25 & \textless{}0.001 & 1.06 & 1.037 & 1.083 \\
SIMD Decile: :meds\_grp9+ & 0.065 & 0.011 & 6.092 & \textless{}0.001 & 1.067 & 1.045 & 1.09 \\
Age: 70-74:meds\_grp3-5 & -0.277 & 0.126 & -2.205 & 0.027 & 0.758 & 0.592 & 0.97 \\
Age: 75-79:meds\_grp3-5 & -0.509 & 0.117 & -4.34 & \textless{}0.001 & 0.601 & 0.477 & 0.756 \\
Age: 80-84:meds\_grp3-5 & -0.643 & 0.112 & -5.74 & \textless{}0.001 & 0.526 & 0.422 & 0.655 \\
Age: 85-89:meds\_grp3-5 & -0.743 & 0.114 & -6.521 & \textless{}0.001 & 0.476 & 0.38 & 0.595 \\
Age: 90-94:meds\_grp3-5 & -0.77 & 0.13 & -5.928 & \textless{}0.001 & 0.463 & 0.359 & 0.597 \\
Age: 95 Plus:meds\_grp3-5 & -0.82 & 0.187 & -4.373 & \textless{}0.001 & 0.44 & 0.305 & 0.636 \\
Age: 70-74:meds\_grp6-8 & -0.222 & 0.121 & -1.831 & 0.067 & 0.801 & 0.631 & 1.016 \\
Age: 75-79:meds\_grp6-8 & -0.596 & 0.113 & -5.258 & \textless{}0.001 & 0.551 & 0.441 & 0.688 \\
Age: 80-84:meds\_grp6-8 & -0.856 & 0.108 & -7.891 & \textless{}0.001 & 0.425 & 0.344 & 0.526 \\
Age: 85-89:meds\_grp6-8 & -1.065 & 0.111 & -9.633 & \textless{}0.001 & 0.345 & 0.278 & 0.428 \\
Age: 90-94:meds\_grp6-8 & -1.189 & 0.126 & -9.413 & \textless{}0.001 & 0.305 & 0.238 & 0.39 \\
Age: 95 Plus:meds\_grp6-8 & -1.278 & 0.183 & -6.99 & \textless{}0.001 & 0.279 & 0.195 & 0.399 \\
Age: 70-74:meds\_grp9+ & -0.479 & 0.114 & -4.216 & \textless{}0.001 & 0.619 & 0.496 & 0.774 \\
Age: 75-79:meds\_grp9+ & -0.886 & 0.106 & -8.344 & \textless{}0.001 & 0.412 & 0.335 & 0.508 \\
Age: 80-84:meds\_grp9+ & -1.245 & 0.102 & -12.234 & \textless{}0.001 & 0.288 & 0.236 & 0.352 \\
Age: 85-89:meds\_grp9+ & -1.764 & 0.104 & -16.887 & \textless{}0.001 & 0.171 & 0.14 & 0.21 \\
Age: 90-94:meds\_grp9+ & -2.15 & 0.121 & -17.721 & \textless{}0.001 & 0.116 & 0.092 & 0.148 \\
Age: 95 Plus:meds\_grp9+ & -2.259 & 0.179 & -12.625 & \textless{}0.001 & 0.104 & 0.074 & 0.148 \\
simd:councilAngus & -0.034 & 0.013 & -2.629 & 0.009 & 0.966 & 0.942 & 0.991 \\
simd:councilEast Ayrshire & 0.017 & 0.012 & 1.429 & 0.153 & 1.017 & 0.994 & 1.041 \\
simd:councilInverclyde & 0.01 & 0.012 & 0.814 & 0.415 & 1.01 & 0.987 & 1.033 \\
simd:councilSouth Lanarkshire & 0.011 & 0.01 & 1.065 & 0.287 & 1.011 & 0.991 & 1.03 \\
simd:councilStirling & 0.023 & 0.013 & 1.812 & 0.07 & 1.023 & 0.998 & 1.049 \\
simd:councilNorth Ayrshire & 0.019 & 0.011 & 1.686 & 0.092 & 1.019 & 0.997 & 1.042 \\
simd:councilDumfires and Galloway & 0.044 & 0.013 & 3.408 & 0.001 & 1.045 & 1.019 & 1.072 \\
simd:councilArgyll and Bute & 0.013 & 0.016 & 0.818 & 0.414 & 1.013 & 0.982 & 1.045 \\* \bottomrule
\end{longtable}
\end{landscape}





