---
output: pdf_document
---

\chapter{Literature Review}\label{ch:lit-review}

\section{Introduction}\label{sec:lit-review-intro}

**Introductory paragraph with link from Thesis introduction - also may require explanation of lack of structured lit search**

Many countries, including the United Kingdom (UK), have recently seen policies implemented that aim to integrate the provision of health and social care services [@RN234; @RN362; @RN262]. In addition to reducing variations in the provision of care across geographic areas, these policies hope to save public money by reducing unplanned admissions and delayed discharges from hospital whilst also improving the quality of services for individuals [@RN232; @RN266]. The World Health Organisation [-@RN320] cites relative inequalities in improvements of health and life expectancy, within and between countries, as justification for recommended structural change to healthcare. The main recommendation is for governmental policy to shift healthcare focus from acute hospital care to outpatient and community care [@RN320]. The paradigm shift in the method of service delivery is suggested in response to increasing long-term, chronic conditions forming the major burden of care worldwide. Acute secondary care is expensive, thus the shift in care also reflects the need to find affordable models of healthcare in an age of diminishing budgets worldwide [@RN320]. Integrating health and social care services and increasing primary care spend are cited as two potential ways of facilitating this shift in focus [@RN320]. Policies introduced that facilitate integration of services have been implemented despite little evidence to suggest they will have the desired effect [@RN367; @RN369; @RN234; @RN233; @RN321; @RN362; @RN366; @RN260]. The continued drive to integrate services does, however, implicitly acknowledge that health and social care services are linked. How these services interact at the individual level and whether differing levels of provision in each service affects the other is not well understood [@RN361; @RN205].

Provision of social care has become one of the most important issues for policy makers in the UK in recent years [@RN250]. In Scotland, approximately two-thirds of individuals receiving social care services are over the age of 65 [@RN128] whilst approximately two-thirds of all those over the age of 65 have multimorbidity (two or more health conditions) [@RN33]. It would seem intuitive that a large proportion of those receiving social care (if not all) have multimorbidity. However, no single data source exists that allows this comparison to be made. Nevertheless, guidelines exist for healthcare professionals to assist in assessing the social care needs of older people with multiple long term conditions [@RN150]. Multimorbidity is associated with a number of negative outcomes including increased health care usage [@RN226]. Whether multimorbidity increases use of social care services is unknown but this could have an important role in informing policy decisions regarding social care provision. 

Levels of multimorbidity in the Scottish population follow a stark socioeconomic profile with those of lower socioeconomic position having higher levels of multiple conditions and more complex care needs [@RN33; @RN21]. This inequality in outcome is compounded by the fact that primary care provision in areas of higher socioeconomic disadvantage, and thus areas of higher need, receive the same or less funding as other more affluent areas. This inequity in provision of service demonstrates existence of the inverse care law in primary care services [@RN120; @RN39; @RN148] which states, "The availability of good medical care tends to vary inversely with the need for it in the population served [@RN120]." Little is known about how access to social care differs across socioeconomic and geographic strata. Health services are free to access at the point of need whereas social care is provided by Local Authorities and access is regulated by eligibility criteria. In an age of austerity, the question of whether an inverse *social* care law exists remains unanswered.     

Until recently many local authorities had attempted to protect front-line services, such as social care, from austerity cuts [@RN117]. However, given continued year-on-year reductions and a further 7.2% cut to local authority spending in 2016/2017 [@RN251], the ability to protect social care from reductions in spend becomes less likely. Decreased local government budgets across the UK and Scotland since 2010 have affected those living in the poorest areas hardest [@RN117; @RN235]. If social care budgets decrease further, the question of whether the most deprived areas will feel these cuts most is of grave importance.

The overall aim of the PhD project is to empirically explore these issues. This chapter will specifically review literature regarding the three main themes outlined above namely; social care, the interaction of health and social care services, and  multimorbidity. Section \ref{sec:access-sc} reviews definitions, international models, and variation in access to social care. Section \ref{sec:hsc-interaction} outlines the policy framework regarding health and social care services, how these services are funded and delivered, and why they are linked. It then describes the legislation that made health and social care integration law in Scotland before reviewing empirical evidence of the nature of the interaction between health and social care services. Finally, Section \ref{sec:mm} describes why multimorbidity is important in the context of health and social care integration and then provides an overview of academic literature and policy documents regarding multimorbidity and its definitions, measurement, and epidemiology.

\section{Access to Social Care}\label{sec:access-sc}

\subsection{Definitions}\label{subsec:access-sc-defs}

**Need to add in OECD(2011) definition**

As in the case of multimorbidity, discussed in section \ref{subsec:mm-defs}, there is no internationally (or nationally) accepted definition of social care. Indeed, the difference between what is social care and what is health care has no clear line of demarcation resulting in local variation in provision of services [@RN371]. A recent NICE guideline [-@RN150] addressing social care needs for older people with multiple chronic conditions, used a definition provided in the UK Health and Social Care Act [-@RN149]:-
\begin{quotation}
	““Adult social care”—
	(a) includes all forms of personal care and other practical assistance provided for individuals who, by reason of age, illness, disability, pregnancy, childbirth, dependence on alcohol or drugs, or any other similar circumstances, are in need of such care or other assistance, but 
	(b) does not include anything provided by an establishment or agency for which Her Majesty’s Chief Inspector of Education, Children’s Services and Skills is the registration authority under section 5 of the Care Standards Act 2000.”
	(The Health and Social Care Act  2012 c7, Part 3, Chapter 1, Section 65, Subsection 4)
\end{quotation}  
The NICE guideline [-@RN150] advises that social care planning for people with multimorbidity should include holistic assessment of biopsychosocial factors including sexual, spiritual, cultural, and communication needs as well as considering access to leisure and social activities incorporating issues regarding mobility and transport. Specifically, the guideline cites; self-care, taking medicines, learning, volunteering, maintaining a home, financial management, employment, socialising with friends and hobbies as activities that all patients should be able to take part in should they wish and social care assessment should assess the ability of the individual to achieve this. 

A more succinct definition of social care is used in a report to the Minister for Care Services at the UK Department of Health, :- 
\begin{quotation}
	"The group of services that provide personal care and support to people in social situations – such as family; the community; a communal setting; to help them achieve independence and to promote their positive contribution as citizens." Platt [-@RN154, pp. 4]
\end{quotation}
Huxley et al. [-@RN153] are critical of this service-based definition and argue that social care is intended to improve general well-being for those that are in need. As quality of life is an important factor of well-being, Huxley et al. [-@RN153] argue that wider issues regarding environment and the quality of public and private services also play an important role in social care. Indeed, Daly and Lewis [-@RN146, pp.287] argue that social care is “…an activity and set of relations lying at the intersection of state, market, family (and voluntary sector) relations.”

This view is reflected in an aspirational constitution for social care published by an independent, cross-party think-tank [@RN136]. The authors argue that all citizens should have an equal ability to live and control a full and active life. Where this is not possible the state should have a duty to provide the necessary help, in whatever form that is required, to individuals who require it.

A more clearly defined concept is that of *personal care* which has been provided for free in Scotland since 2002. The legislation introduced by the then Scottish Executive necessitated a clear definition and constitutes six dimensions [@RN373]. 

a) Personal Hygiene: washing etc.  
b) Personal Assistance: help with dressings, prostheses etc.  
c) Continence Management: toileting, catheter management etc.  
d) Food and Diet: help with eating, food preparation etc.  
e) Problems of Immobility:  
f) Simple Treatments: help with medicines, creams, oxygen therapy etc. 
[@RN373, pp.256]

Personal care is, however, only one aspect of social care provision and clear definitions of other services provided to individuals are lacking. 


\subsection{International models of social care}\label{subsec:access-sc-models}

The provision of social care is of increasing policy importance across western, post-industrial societies [@RN342; @RN343; @RN344; @RN345]. There are four ways in which social care can be provided to those in need: informally via family or community, formally via voluntary non-profit organisations, formally via the state, or formally via a for-profit organisations [@RN346]. In Europe, increasing demand from users has led to many welfare systems being unable to adequately provide care [@RN344]. Changes in demography, the labour market, democracy, and values have all contributed to the increasing pressure on care services [@RN342]. There is wide consensus that lower birth rates and higher proportions of older people mean that a gap has emerged in the number of adult children able to provide informal care to their parents [@RN342; @RN343; @RN344; @RN346; @RN345]. Traditionally, informal care was provided by women. As gender equality improves, more women are employed outwith domestic circumstances which also reduces the pool of informal social care available [@RN342]. Anttonen [-@RN342] also cites changes in societal attitudes from "familism" to "individualism" as having an impact on informal care resources. These combined factors mean that formal care services are increasingly required to provide social care. 

The pressures on formal social care services has seen increased discussion and comparison of models of care across Europe over the last 20 years [@RN347; @RN348; @RN346; @RN349]. In broad terms, there is agreement that four main European social models exist although, more recently, the lines between these models are beginning to blur [@RN343]. The models have been classified as the: Nordic, Mediterranean, Continental, and Anglo-Saxon models [@RN347; @RN348; @RN346]. There is some variation in the how these models are labelled - for this discussion the most recently described nomenclature is used [@RN348; @RN349]. It must also be noted that the models below detail broad similarities in provision of social care, differences in delivery of services remain between countries within each model. 

The Nordic model of social care describes high levels of universal home and institutional social care funded through taxation or nationalised insurance with little or no role for private insurance [@RN348; @RN346; @RN349]. This model is found in Scandinavian countries such as: Sweden, Denmark, Finland, and the Netherlands and has strong local government influence on the delivery of services [@RN348; @RN346; @RN349].

In contrast. the Mediterranean model of social care (generally found in Greece, Italy, Portugal, and Spain) has very low intervention from local or national government with the majority of social care being informal and provided by family members [@RN348; @RN346; @RN349]. As this role is traditionally carried out by women, the Mediterranean model has attracted criticism from a feminist perspective [@RN346]. 

The Anglo-Saxon model of social care is used to describe the systems used in the UK and, perhaps as a misnomer, Ireland [@RN348; @RN346; @RN349]. The system is also characterised by informal care but has provision of extensive state-funded social care for those in the most need. The model has also been referred to as "means tested", or "the Beveridge model" [@RN346] and increasingly involves service provision from the private sector, particularly in terms of residential care [@RN346]. 

Most commonly found in Austria, Belgium, France, Germany and Luxembourg, the Continental model of social care also has a strong role for informal family care [@RN348; @RN346; @RN349].  The main difference in this model is in the delivery of formal care via non-governmental or religious organisations with funding provided by the state - also known as the subsidiarity model [@RN346].

The 4 models have not only been used to  describe variations in methods of social care delivery, but also to describe the wider model of welfare and social services within each group [@RN349]. As part of a wider social model of care, the Nordic model has a strong re-distributive effect and has the greatest effect of the four models at reducing income equality and poverty [@RN349]. The Mediterranean model performs worst in this respect as does the Anglo-Saxon model when considering incidence of poverty after taxes and transfers [@RN349]. 


There is a remarkable similarity in the description of the change from institution to home-based social care described by Deusdad et al. [-@RN343] and the shift in balance of health care recommended by WHO described in section \ref{sec:lit-review-intro}. It is likely they describe the same phenomenon. WHO [-@RN320] cite integration of health and social care as a potential process of moving care balance for treatment for non-acute, chronic conditions. Older individuals in this category are likely to have social care needs also. There have been large structural changes to delivery of social care in a number of European countries [@RN344]. Deusdad et al [-@RN343] argue that de-institutionalisation and the policy shift in balance of care has disguised reduction in state-funded social care support in some countries. 

\subsection{International variation in access to social care}\label{subsec:access-sc-int-variation}

This section will review literature regarding how the different models of social care described in subsection \ref{subsec:access-sc-models} influence access to social care across countries. This is a new section and requires further reading and synthesis

A recent examination of the effects of the 2008 financial crisis on the way social care is delivered across Europe suggests that the distinctions between the 4 social care models is beginning to blur [@RN343]. There is evidence of a mixture of informal, semi-informal (i.e. black market), and formal care emerging as a more regular model for care delivery in Mediterranean countries whereas, in Nordic countries, an increase in family-based informal care is being observed [@RN343; @RN358]. A shift from residential to home-based care, in tandem with the marketisation of the care sector, has seen a gradual move away from universalism in Scandinavian countries and a greater emphasis on informal care and non-state care being seen across the continent [@RN343].

\subsection{Access to Social Care in the UK I - Resource allocation}\label{subsec:access-resources}

This section will discuss social science theory of fair allocation of resources to Local Authorities such as "the strategy of equality." Will need to outline how social care is funded in the UK Here, the "inverse care law" will also be discussed. 

Evidence and literature of how funding is distributed will also be presented. 


\subsection{Access to Social Care in the UK II - Eligibility}\label{subsec:access-sc-nat-variation}

This section will variation in access to social care *within* Local Authorities. Theory regarding "Street level Bureaucracy" and "Candidacy" will be described.

Literature and evidence of how eligibility affects access will also be presented. 

Access to social care in Scotland is means tested via assessment carried out by a social worker. The criteria for social care delivery, therefore, has a very important part to play in how services are accessed. This section describes relevant literature on how eligibility criteria are set.

In 2010 the Scottish Government published a report identifying a strategy for the policy of self-directed support [@RN171]. The report was written in conjunction with the Convention of Scottish Local Authorities\ (COSLA) and included the recommendation that the National Eligibility Framework developed by the Sutherland review into free personal and nursing care [-@RN172] should be applied across all social care services. The framework has four criteria for assessing risk in relation to a person’s care needs: Critical, Substantial, Moderate and Low [@RN184]. The Critical and Substantial levels of risk indicate social care needs should be addressed immediately or imminently, whereas a moderate level of risk may indicate either some or no services being required. There is no explicit description of severity or which care needs fall into each category and in practice each Local Authority sets the criteria and decided at which level of risk they would provide social care [@RN170].

Equity of access to services is directly influenced by an eligibility framework. Indeed, the Strategy for Self-Directed Support [@RN171, pp.20] acknowledges this and states that such a framework “…can result in resources being narrowly focused on individuals with acute needs.” However, the report goes on to state that growing demand and finite resources requires some form of eligibility assessment but this should not have a disproportionate effect on any one group of people requiring care.

The eligibility framework allows each Local Authority to set thresholds for access to care in line with local priorities and resources. This has the effect that access to services varies across differing council areas. The potential for regional variation is again acknowledged by the Strategy for Self-Directed Support [@RN171, pp.20] which states that, “…further work will be undertaken by the Scottish Government and COSLA to assess whether there is merit in establishing national thresholds for access to formal support across all client groups.”

Acknowledgment of problems with eligibility criteria and the promise of “further work” to be undertaken by the Scottish Government and COSLA is repeated in practitioner guidance on Self-Directed Support published in 2014 [@RN170, pp.19] and that , “…it remains the case that local authorities should operate eligibility criteria to determine whether or not an individual assessed as having social care needs can access formal support and if so, which of their needs are to be met by that support.”

Data is not available on levels of care provided by LAs for each of the National Eligibility Framework criteria or for the threshold that each LA provides care at. The Scottish Government collects an annual report of eligibility and waiting times for the 1st quarter of the year. The latest report [@RN184] provides information on the time individuals had to wait to receive assessment and the time individuals had to wait to receive care in the period January-March for the preceding 5 years. However, no absolute numbers of people in each category is provided.

The Scottish National Eligibility Framework has striking similarities to that formerly used in England and described in Fair Access to Care Services (FACS) produced by the Social Care Institute for Excellence (SCIE) [-@RN138]. Exactly the same nomenclature is used to describe the eligibility categories of need. Newton and Browne [-@RN163] critiqued a previous version the FACS guidance and found similar issues to those raised above regarding regional variations in service and concentration of services on those with the highest need. Their paper describes further issues with access to social care in the context of social theory described by Lipsky [-@RN174] and “Street level bureaucracy” where intentional and unintentional judgment of entitlement by social care workers have an impact on whether an individual receives care or not. Newton and Browne [-@RN163] also make the assertion that health and social care has never been accessed equitably by arguing that those with a greater ability to articulate needs and negotiate access are more likely to gain access to services. Although no citation is provided to back-up this argument it has certainly been described elsewhere [@RN118] and sits well in the broader discussion of inequitable access to services [@RN116; @RN175; @RN120].

In England, the Care Act [-@RN176] aimed to remove regional variations in eligibility in access to social care by imposing national minimum thresholds that Local Authorities would have a statutory obligation to provide. The Care Act also aimed to ensure Local Authorities provided care, “…as early as possible to help maintain well-being and independence, and potentially delay a situation where longer-term care and support might be required.” [@RN169, pp.2]. The minimum criteria for being eligible for care involves an individual having needs that impairs their ability to meet 2 or more of a designated list of outcomes (e.g. managing and maintaining nutrition or maintaining hygiene) [@RN169] and is set by the Secretary of State for Health [@RN177].

In practice, the most likely outcome is that the minimum threshold that Local Authorities will have to provide care will be similar to the “Critical” level of the National Eligibility Framework previously used in the FACS guidance [@RN173; @RN177] (and similar to that used in Scotland). This will legalise a shift that has already been occurring in England where fewer numbers of LAs are providing care for those with “moderate” needs and only providing care for those with “critical” needs [@RN173; @RN177]. Burchardt et al. [-@RN173] state that only 2% of English LAs will have to widen their care threshold whereas 12% could now, legally, tighten care provision as a result of the Care Act. This situation is not new and has been gradually worsening over the past decade and has profound impacts on the quality of, and access to, social care. Indeed:-
\begin{quotation}
"It is through the eligibility criteria that resources are rationed, that is "need" is equated with "resources available". This mechanism severely limited the idea that provision could be determined either by need or by the right to services."
\end{quotation} [@RN374, pp.10]

A recent report by the House of Commons Communities and Local Government Committee [-@RN287] confirmed reductions in the absolute number of people receiving care, the concentration of services in those with highest needs only, reduction in quality of care provided, and the resulting pressures this caused to the health service through increased emergency admissions and delayed discharges. The report highlights the perilous state of social care provision in England and urges immediate attention from the government to address funding shortfalls. 

Burchardt et al. [-@RN173] and Abrahams et al. [-@RN177] recognise some positive changes to Social Care policy through the Social Care Act but are damning about past UK Government Social Care policy in England and Wales. They cite chronic underfunding and cuts for over ten years resulting in fewer numbers of people receiving care at a time when demand is sharply increasing due to demographic change. The “intensification” of services on those with the most acute needs is cited by both sets of authors as counterproductive – ignoring those with moderate care needs completely derails one of the main purposes of the Care Act, preventative services. Indeed, \begin{quotation}
	“As well as lacking in moral sense, such an approach is economically unsound. Waiting for people to have high needs before providing care means that care will be more expensive, as well as pushing more older people into an already pressurised NHS. ” \end{quotation} [@RN177, pp.5]

A similar picture has been seen in Scotland. Absolute numbers of people receiving home care has steadily fallen over the last 10 years whilst the number of hours of care provided has increased [@RN128]. There are wide variations in the number of hours of home care provided per population across Local Authorities [@RN128]. This may reflect different demographic make-up of each Local Authority although reductions in ratios per population can be seen in almost all Local Authorities [*edit - I can produce a table here to reflect this but is that appropriate in the Intro? Also would have to provide code in the Appendix to show how I produced the table*].

In a report profiling the care at home sector in Scotland. MacLeod and Mair [-@RN147] describe large decreases in absolute numbers of people receiving care at home over the ten years to 2013. There have also been significant reductions in the number of people receiving non-personal care (so called “mopping and shopping”). The increase in the number of hours of home care delivered by all services reflects a focus on smaller numbers of individuals with higher care needs. This means those with moderate or low personal care needs and those requiring “mopping and shopping” services are now less likely to receive publicly funded care. Echoing the views of Burchardt et al. [-@RN173] and Abrahams et al. [-@RN177], Macleod and Mair [-@RN147] highlight the potential false economy of this situation – home care services are likely to reduce the need for costly emergency admissions to hospital and delay the requirement for more intensive home care packages.

\subsection{Health inequalities}\label{subsec:health-inequals}

This section will outline why access to services are linked to health inequalities (with reference to section \ref{subsec:access-resources}). Then summarise main literature on health inequalities (briefly).

In the UK, poverty remains the largest predictor of relative ill health and has associations with increased morbidity, multimorbidity, and decreased life expectancy [@RN37]. People living in deprived areas are more likely to engage in unhealthy lifestyle behaviours, experience multimorbidity at a younger age, and live in overcrowded or unsuitable housing [@RN37; @RN311]. The influential Marmot review into health inequalities found that those in the most deprived areas of England die, on average, 7 years earlier than their most affluent peers [@RN312] with the gap in life expectancy increasing between 1995 and 2008 [@RN313]. Subsequent research by the King’s Fund suggests the gap in life expectancy reduced between the periods 1999-2003 and 2006-2010 [@RN314]. The report warns that this improvement may be due to the spending and policy decisions of the New Labour Government of the early 2000s and that recent austerity measures in the UK may undermine the progress made [@RN314]. Indeed, the most recent analysis released by the Office for National Statistics [-@RN375] suggests the gap in male life expectancy in England is now 9.1 years. In Northern Ireland, the male life expectancy gap is the lowest of all 4 UK nations, however those in the poorest neighbourhoods die, on average, 4 years earlier than those in the most affluent areas [@RN375]. In Wales the gap is slightly larger at 4.2 years [@RN375]. There is a gap of 7 years in life expectancy at birth in Scottish males - those born in East Dunbartonshire can expect to live to 80.5 years, whereas those in Glasgow city can expect to live 73.4 years [@RN375]. In Scotland, the Government reports statistics on healthy life expectancy which is defined as the number of years people can expect to live in good health [@RN315]. The most recent figures suggest men and women in the most deprived areas can expect to become ill 25.1 and 22.1 years earlier than their most affluent peers respectively [@RN315] meaning Scotland has the highest levels of health inequalities in western and central Europe [@RN385; @RN386]. 

These disparities in life expectancy are compounded by inequities in access to health services. The inverse care law - the availability of good medical care varying inversely with the need for it in the population served [@RN120] - persists. As discussed above, the most deprived areas have lower life expectancy and higher morbidity figures and therefore greater health needs [@RN37]. However, the poorest neighbourhoods in England have been reported to have 62.5 General Practitioners (GP) per 100,000 population whereas the most affluent neighbourhoods have 76.2 per 100,000 [@RN317] suggesting health provision does not match need. Recent planned changes in policy to distribute primary care funding based on population age are likely to exacerbate this situation [@RN39]. Indeed, increases in workload with deteriorating proportions of budgets has lead the King’s Fund to describe the situation in primary care in England and Wales as, “in crisis” [@RN318, pp.3]. In Scotland, the  even distribution of GP workforce among the population means GP practices in the most deprived areas need to provide more consultations, for people with greater needs, at the same funding level as practices with fewer resource demands [@RN148; @RN27]. Poorer access to primary health care is associated with greater demand for unnecessary admission to hospital [@RN49; @RN268] which is responsible for high proportions of healthcare expenditure. Studies with interventions to improve access to primary care have shown reductions in unnecessary secondary care use [@RN245; @RN246; @RN272] providing an economic, as well as moral, case for primary care investment. As acute hospital admission rates rise, tackling health inequalities is a major policy priority and primary care can play a pivotal role in this action [@RN319].

There are many theories as to why inequalities in health exist across social class [@RN327; @RN333]. Some of these, such as statistical artefact and biological reasons, were rejected as being implausible by the Black report [@RN277]. To a large extent, epidemiological evidence and theoretical argument has agreed with that view [@RN327; @RN83; @RN82; @RN333]. There have been many critiques of the theories proposed in the last 35 years which focus on differing numbers proposals [@RN327; @RN333; @RN377; @RN378; @RN83]. Whilst arguments over which theory is most plausible to explain the cause of health inequality, most researchers agree on ways to remedy disparities in health outcome namely the redistribution of income, wealth and political power [@RN378; @RN391; @RN327; @RN333]. Although health services have an important role to play, it is the "upstream" policies of redistribution that will make the biggest impacts in improving health outcomes across society [@RN378; @RN391; @RN327; @RN325]. Whilst this has been known for some time, government policies in the UK to date have not addressed these issues and have thus failed to make meaningful improvements in health inequalities [@RN330; @RN331; @RN377].

\subsection{Summary}\label{subsec:access-sc-summary}

A summary of the literature presented in section \ref{sec:access-sc}

Varying definitions of social care. Differing European models described in literature - all now showing signs of change due to impact of ageing population. (Findings of differing access across these models section). Two main social theories with regard to access to services. One about allocation of resources, other about distribution of resources by providers. 

Social care is an increasing policy priority across Europe due to demographic trends and reductions in the amount of state-based funding available to provide care. All countries, regardless of model of social care, have seen increases in market-based systems and increased use of private care. The boundary between health and social care is not clearly defined. In the UK this means provision of services is decided locally which is likely to result in variation in provision and therefore outcomes. Devolution has resulted in variations in policy across the UK, most notably in the free provision of personal care in Scotland. However, there have been marked reductions in the amounts of social care delivered in both England and Scotland largely due to tightening of access to services through eligibility criteria. This has led to warnings that reduction in service provision is likely to be counter-productive in terms of service experience and cost to governments. 

\section{Health and Social Care Interaction}\label{sec:hsc-interaction}

\subsection{Public Policy}\label{subsec:policy}

Section discussing public policy of health and social care. Two silos. Short description of NHS funding and compared with LA funding described in subsection \ref{subsec:access-sc-nat-variation}. 

Discuss why these services are linked - hosp discharge etc. 

Highlight current policy such as 2020 vision in Scotland, Health and Social Care Act (2012)(UK) **Christie Commision** etc.

Discuss Why poor co-ordination between services? 

\subsection{Health and Social Care Integration}\label{subsec:hsc-integration}

Overview of health and social care integration. What it aims to do. Why etc. 

Policy - The Act - structure such as "Lead Agency" or "Joint Body" models. 

Evidence of benefits of integration - (not much!)


\subsection{Research on Health and Social Care Interaction}\label{subsec:research}

Section discussing the few studies that have aimed to assess the interaction between health and social care services. 

Bardsley et al[-@RN183] a good starting point - also studies identified by mini lit search in 1st year review plus update.

\subsection{Summary}\label{subsec:hsc-interaction-summary}

Summary of literature presented in section \ref{sec:hsc-interaction}

\section{Multimorbidity}\label{sec:mm}

\subsection{Why focus on Multimorbidity?}\label{subsec:why-mm}

Important subsection. Brief definition - Identify high use of health care and association with poor outcomes (with citations). Then make case that use of social care likely to be associated with MM (though no evidence to back this up - hence need for thesis). 

Discuss whether access to social care likely to be more or less "fair" for those with MM - ref to Inverse Care Law and PC literature. 

Will Health and Social Care integration results in better or worse outcomes for MM? (Should be better - main aim of integration..)

Link to following sections as background of current MM literature to help inform understanding of concept

\subsection{Definitions}\label{subsec:mm-defs}

Despite the increasing importance of multimorbidity on health care systems, there is no internationally agreed definition of the term or concept [@RN89; @RN95]. Van den Akker et al [-@RN19] first made the distinction between the terms comorbidity and multimorbidity. Comorbidity was originally described by Fenstein [@RN338, pp.467] who stated, "In a patient with a particular index disease, the term co-morbidity refers to any additional co-existing ailment." Van Den Akker et al. [-@RN19, pp.65] used the term multimorbidity to describe, "...any co-occurrence of medical conditions within a person." In this sense, multimorbidity does not rely on the presence of a primary, or index, disease but refers to the overall state of multiple illnesses.  

Further development of definitions is provided by Valderas et al. [@RN64] who characterise the construct of the term comorbidity found in the literature in four main groups; (a) comorbidity – additional diseases in the context of an index disease, (b) multimorbidity – more than one disease within an individual (without reference to an index disease), (c) morbidity burden – total impact of physiological dysfunction linked to patient outcomes and (d) patient complexity – the effect of non-health characteristics (e.g. deprivation, culture, environment) on morbidity burden.

Valderas et al. [@RN64] discuss these four constructs of comorbidity further in relation to three main research areas; clinical care, epidemiology and public health, and health service planning. It is suggested that comorbidity may be a more valid definition for use in specialist clinical care, whereas multimorbidity and morbidity burden would be more appropriate in primary care research. In epidemiological and public health research, the definitions of either comorbidity or multimorbidity would be of use depending on the origin of the diseases being studied and the particular research questions being investigated. Morbidity burden and patient complexity are, according to Valderas et al. [@RN64], the most appropriate definitions for research exploring healthcare use and costs. 

A further definition of multimorbidity is offered by the European General Practice Research Network (EGPRN) who report findings of a systematic review in the construction of their definition. Citing over 100 different definitions for multimorbidity in academic research the EGPRN [@RN77, pp.1] aimed to clarify the concept of multimorbidity and define the term as 
\begin{quotation} "...any combination of chronic disease with at least one other disease (acute or chronic) biopsychosocial factor (associated or not) or somatic risk factor." \end{quotation} This definition goes some way to capture the complexity of the concept of multimorbidity as explained by Valderas et al. [-@RN64] but has not ended debate on the matter.

More recently, a systematic review focused on which diseases, risk factors and symptoms are included in varying definitions of multimorbidity [@RN254]. Whilst the majority of included studies in the review indicated multimorbidity as the presence of two or more conditions, Willadsen et al [-@RN254] found the total number of diseases, risk factors, and symptoms used varied from 4 to 147. Of the 167 included articles in the review, 115 different ways of defining multimorbidity were identified [@RN254]. 

In a recently published guideline, the National Institute for Health and Care Excellence (NICE) [@RN226] acknowledge the complexity of defining multimorbidity. NICE agree with other commentators [@RN21] that basing the definition of multimorbidity on 2 or more health conditions only does not fully capture a clinically meaningful picture of the concept. The guideline highlights the fact that many people defined as multimorbid in this way may not be ill and have excellent quality of life requiring little or no health care input [@RN226]. For this reason the guideline is aimed at people with more than 1 long-term condition with any of the following:-

* Difficulty managing treatments or day-to-day activities.
* Care from multiple services and requiring care from a new service.
* Both long-term physical and mental health conditions.
* Frailty.
* Frequent use of unplanned or emergency care.
* Prescription of multiple, regular medicines. 

[@RN226]

Although multimorbidity may seem to be an intuitive thing to understand, defining a useful concept of the term is much more difficult [@RN155]. Whilst the co-occurrence of 2 or more long-term conditions is the most commonly used definition of multimorbidity, there are wide variations in the number of conditions from which this definition can be based. This lack of clarity means that identifying useful ways to measure Multimorbidity is also problematic with marked variations in approaches.

\subsection{Measurement}\label{subsec:mm-measures}

The findings of three recent systematic reviews have highlighted the myriad ways researchers have approached the measurement of multimorbidity [@RN16; @RN34; @RN29]. Each review aimed to collate evidence of measurement tools in comorbidity or multimorbidity but from different perspectives: De Groot et al [-@RN16] searched for comorbidity indices to inform research into Multiple Sclerosis, Diederichs et al [-@RN34] specifically searched for multimorbidity measurement indices, whereas Huntley et al [-@RN29] searched for measures of multimorbidity used only in primary care research. The systematic reviews found 13, 39 and 17 exclusive ways of measuring multimorbidity or comorbidity respectively. The number of medical conditions included in these measurements varied from 4 to 102 [-@RN34]. Most indices are developed from secondary care populations but many have been adapted for other populations including primary care [@RN34; @RN29].

There are two main ways of measuring multimorbidity: simple disease counts or using an index which applies weights to either prescribed medications or medical conditions and other factors in an attempt to explain severity of illness [@RN16; @RN34; @RN29]. In primary care research, the most frequently used measurement is simple disease counts [@RN29]. This may because of the ease with which it can be administered compared to more complex indices such as the Charlson index [@RN339] or Chronic Disease Score [@RN340] and their variations. Despite the large number of multimorbidity indices available, Huntley et al [-@RN29] cite evidence that suggests simple counts of diseases or medications are almost as effective as the more complex indices at predicting mortality or health care use in the primary care setting. However, when aiming to predict mortality in Primary Care, Huntley et al [-@RN29] recommend the best measurement of multimorbidity to be provided by the Charlson index [@RN339] and its variations. Measurement of multimorbidity in relation to primary care healthcare use can be predicted with equivalence by either; the Adjusted Clinical Group system [@RN341], the Charlson index [@RN339], or disease counts [@RN29]. Disease counts were also found by Huntley et al [-@RN29] to have good evidence to suggest they provide a robust measure of multimorbidity in relation to Quality of Life, as does the Charlson index [@RN339]. A count of medicines was found to be a good predictor of primary care use and mortality in a more recent paper [@RN247]. In their paper, Perkins et al [-@RN78] argue that indices developed in the secondary care setting, such as the Charlson index, should be used with caution in other settings despite adaptions. More recently, Wallace et al [-@RN228] found little difference between simple (count) and complex (index) measures when predicting hospital admission but noted that all measures of multimorbidity alone were poor predictors of the outcome. 

An emerging method of measuring multimorbidity is to identify clusters of medical conditions that co-exist in individuals at rates higher than would be expected - or non-random prevalence. Recent research and academic discussion suggests identification of disease clusters may enable clearer answers to clinically relevant research questions than currently employed measures [@RN96; RN109; @RN98; @RN99; @RN188; @RN31; @RN64]. Statistical techniques employed in attempts to identify such clusters include: factor analysis, cluster analysis, the observed-to-expected ratio, multiple correspondence analysis [@RN98; @RN301], principal component analysis, latent class analysis [@RN109; @RN365], and machine learning techniques [@RN273]. In their systematic review of clustering methods, Prados-Torres et al [-@RN98] found wide variations in approaches to clustering and characteristics of populations studied. As opposed to many of the studies included in the review, they recommend future attempts at clustering diseases use: population-sized datasets, statistical techniques that are suited to the dichotomous nature of diagnostic variables, and large numbers of conditions from which to form clusters [@RN98]. Prados-Torres et al [-@RN98] identified three groups of patterns common to all included studies in their review despite marked heterogeneity namely; cardiovascular and metabolic diseases, mental health conditions, and musculoskeletal disorders. Whilst identification of groups may have some benefit in terms of identifying causal mechanisms between diseases, whether they are useful or meaningful in clinical terms is a matter of debate.

\subsection{Epidemiology}\label{subsec:mm-epi}

Sections \ref{subsec:mm-defs} and \ref{subsec:mm-measures} describe the wide variations in definitions and measures of multimorbidity. It is, therefore, unsurprising that there is marked heterogeneity in reports of multimorbidity prevalence. Fortin et al [-@RN56] illustrate this by reporting variations in the prevalence of multimorbidity from 3.5% to 98.5% across 21 studies included in their systematic review. The variation in findings is explained by the vastly different populations, settings, data collection techniques, and definitions of multimorbidity used by included studies. A more recent systematic review concentrating on primary care populations and aiming to describe prevalence, causes and patterns of multimorbidity [@RN15] found reports of multimorbidity prevalence between 12.9% and 95.1%. Similar variations in definitions, measures and populations were found. The number of conditions used to estimate multimorbidity prevalence varied between 5 and 335 [@RN15]. In an attempt to standardise conditions to be considered using international disease classification labels, a more recent paper included 60 conditions [@RN300]. Van den Akker et al [-RN91] highlighted the complications that can arise when attempting to measure prevalence of multimorbidity and suggest that certain decisions made in study design will depend on the specific question being interrogated by researchers (e.g. the number of diseases to include in the measure of multimorbidity or the age-range of the sample). The systematic reviews of Violan et al [-@RN15] and Fortin et al [-@RN56] may reflect the varying decisions made by research teams in study design. Despite the difficulties in synthesizing evidence on heterogeneous studies, Violan et al [-@RN15] found strong relationships between multimorbidity and: age, female gender, low socioeconomic status, and mental health across studies in their review. 

\subsection{Summary}\label{subsec:mm-summary}

Multimorbidity is most commonly defined as the presence (or co-occurrence) of 2 or more long-term conditions in an individual. Debate continues as to the type and number of long-term conditions that should be included to provide a meaningful concept for individuals, clinicians and healthcare organisations. The lack of a standard definition is mirrored in the myriad ways of measuring multimorbidity with various counts, indices, and clusters. Despite this, evidence suggests multimorbidity is increasing in prevalence and has a strong socioeconomic pattern. As a result, policy needs to be tailored to account for the complex needs of the increasing numbers of people with multimorbidity.

\section{Conclusion}\label{sec:lit-review-conclusion}

Conclusion of chapter \ref{ch:lit-review}

Access to social care is influenced in 2 main ways - allocation of resources *to* providers and distribution of services *within* providers. Theory and evidence suggest inequitable access possible.

Major policy shift to integrate health and social care services internationally. One of main drivers increase in older population - services currently disjointed for this group. Two-thirds over 65s have multimorbidity and associated poorer outcomes - with social gradient. 

Understanding how this population access social care, therefore, vitally important and under-researched.  

Does an inverse *social* care law exist? i.e. Does the allocation of resources (via funding formulae) to Local Authorities negatively impact on those areas with higher need? 

Furthermore, does access to social care vary across Local Authorities - is there a "postcode lottery" in terms of service provision i.e. does application of eligibility criteria depend on where you live?  

Is multimorbidity status associated with levels of social care provided within *and* across local authorities?   

Important to understand how access to social care influences health care use and mortality - do those with multimorbidity and social care have different outcomes from those with multimorbidity and no social care?

Research questions:- 

In people over the age of 65 in Scotland:

1.	a.	What are the socioeconomic, demographic, and geographic patterns in the use of social care? 
    b.	Is there an association between multimorbidity status and the amount and type of social care use over time? Does this vary by the patterns described in 1(a)?  
    
2.  a.	Is there an association in the use of social care services, multimorbidity status and unscheduled health care use?
    b.	Do multimorbidity status and social care use predict mortality?




