---
output: pdf_document
---

\chapter{Introduction}\label{ch:intro}

Integration of health and social care became law in Scotland on 1st April 2016. Reflects patterns across the developing world to restructure health services to cope with demands of an ageing population. 

Social Care of increasing policy (and political) importance. Link to healthcare (and demands on health services) becoming increasingly apparent (increase delayed discharge etc).

This, in part, due to long-term conditions now major burden of global disease (replacing infectious diseases). Large proportions of population have multimorbidity (OECD) which has a number of negative outcomes including mortality and health care use.

Association of multimorbidity and social care use is unknown. 

PhD funding from Scottish Government to assess these topics. (2020 vision and other policy link)

Important part of the funding to link administrative data sources in order to identify the benefit of this process. 
*Measurement of social (or LTC) is improtant for a number of reseons - OECD(2013) page 18, Care co-ordination (integration) is not measured well pp 76, administrative databases potential to help these problems plus ideas for outcome measures pp 76 & 79, pp81 obstacles to data collection (overcome by data linkage in Soctland??*

(Need WHO policy outlines and other suitable high-level policy docs in this section)

\section{Aims and Objectives}\label{sec:intro-aims-and-obs}

The thesis has both substantive and methodological aims. Substantively, it aims to contribute to the debate surrounding health and social care integration by looking specifically at a group that are likely to be regular users of both health and social care services, i.e. those with multimorbidity. Methodologically, the thesis aims to contribute to efforts to improve the exploitation of administrative data as a means to analyse public service performance and effectiveness. 

Aims of the project are:- 

\begin{enumerate}[noitemsep]
\item Describe and compare social inequalities in the use of social care services using linked health and social care data.
\item Explore the effects of social care use for those with multimorbidity on 
\begin{enumerate} 
\item unscheduled health care use and
\item mortality. 
\end{enumerate}
\end{enumerate}



The objectives of the project are:-

\begin{enumerate}[noitemsep]
\item To assess how access to social care services varies for people with multimorbidity, especially by socioeconomic status.  
\item To assess the impacts of social care service use on health service use and health outcomes for people with multimorbidity, where possible exploiting geographic differences in social care as "natural experiments".
\item To make recommendations for policy on the future of integration of health and social care services based on these results.
\item To assess tho what extant measures of multimorbidity and of health and social care service use can be operationalised using existing linked health and social care administrative data.
\item To make recommendations to policy makers on administrative data collections. 
\end{enumerate}


\section{Scientific contribution}\label{sec:intro-contribution}

Explicit description of what thesis adds to knowledge

\section{Conventions}\label{sec:intro-conventions}

Outline definitions

* Social care refers to Adult social care (with link to subsection \ref{subsec:access-sc-defs})
* Multimorbidity and morbidity burden as opposed to comorbidity (with link to subsection \ref{subsec:mm-defs})

