---
output: pdf_document
---

\chapter{Data}\label{ch:data}

intro paragraph - complete when finshed

\section{Data Linkage}\label{sec:data-linkage}

\epigraph{Record linkage refers to a merging that brings together information from two or more sources of data with the object of consolidating facts concerning an individual or an event that are not available in any separate record.}{\textit{[OECD, 2006]}}

Administrative data is data that is generated when individuals use a service of some description. Often in research terms, and exclusively in this thesis, administrative data refers to data generated by the use of \textit{public} services [@RN85; @RN352]. This data can describe the provision of a specific service or how that service was administred by the provider [@RN85; @RN352]. As the above definition outlines, record linkage involves joining data about individuals from two or more administrative databases together [@RN279; @RN470] and is being increasingly used in social science research [@RN133; @RN276]. 

Using administrative data for research purposes has a number of advantages and disadvantages. The data is not collected for research purposes and as such may lack specific information relevant to a researcher's line of inquiry [@RN352]. This also reduces the ability of a study to adjust for all potential confounding variables, decreasing the ability to make causal inferences from the data [@RN352]. There is the potential for ambiguity about the coding of variables in a database and what each code represents [@RN352; @RN133; @RN398]. This means specialist knowledge of the database and collection methods are required [@RN352]. Coding of health conditions are particularly susceptible to potential mis-classification or under-reporting of certain diseases [@RN480; @RN352; @RN398]. 

Advantages of administrative databases are that they enable large, often population sized, sample sizes because they are generated from service use [@RN352; @RN85; @RN398]. This characteristic also reduces the potential for sampling bias [@RN352]. Well maintained administrative data can offer information over long periods of time including very recent data [@RN85]. This can make inferences from research findings more robust without the extra cost traditional observational studies might incur [@RN352]. The potential to link administrative databases from a number of sources is a significant advantage and offers insghts into how services interact [@RN352; @RN133; @RN398].

There are two main methods of linking data from disparate sources; deterministic matching and probabilistic matching [@RN279; @RN470]. Where differing datasets possess common unique identifiers, determinsitic matching simply links data using this identifier. Probability matching methodology can be employed in the abscence of a common unique identifier [@RN279; @RN470]. Using this method, a probability of two records matching correctly is calculated based on how well the records match based on a set of common partial identifiers such as name, date-of-birth, and postcode [@RN279; @RN470]. An important consideration when using probabilistic linkage is making an assessment of false-positive match rates [@RN279; @RN470]. There are three main strategies to assist with this assessment; measuring error using "gold-standard" data (such as a validated external datasets), sensitivity analyses (comparing results across differing linkage parameters), and comparing linked and unlinked data according to characteristics (such as sociodemographic subgroups) [@RN279]. 

In order to preserve anonymity whilst linking administrative data from different agencies, a method known as "linkage using a separation of functions" is employed [@RN279; @RN85]. This process involves the use of a Trusted Third Party (TTP) to process non-anonymised information in order to link more than one dataset together. The TTP receives personal information (e.g. names, addresses and dates-of-birth) from the data controllers of the adminstrative datasets to be used and creates index "keys" to send back to the data controllers to attach to their data [@RN279; @RN85]. The TTP creates a lookup table of index "keys" relevant to each dataset and sends these to a linkage agent. The linkage agent receives data from the data controllers \textit{without} personal information and links them together using the "keys" created by the TTP and makes this available to a researcher in a secure envirnonment [@RN279; @RN85]. This process means the TTP receives lots of personal information but no other information, the researcher has access to information relevant to their study but no personal information, and the data controllers share information about individuals in their datasets without compromising anonymity [@RN479].

Scotland is home to some of the best administrative databases in the world [@RN85]. This is particularly due to the high-quality of health datasets that have been collected and maintained for over 40 years [@RN85; @RN470]. Whilst linkage of differing health datasets has become common over this period, new cross-sectoral linkages are beginning to emerge such as health and educational data [@RN471], and health and social care data [@RN132]. These cross-sectoral linkages are providing new insights that have the potential to have lasting impact on policy and provision of services [@RN85; @RN133]. 

\section{Infrastructure}\label{sec:infrastructure}

\epigraph{The key test for an acronym is to ask whether it helps or hurts communication.}{\textit{Elon Musk}}

\subsection{Scottish Informatics and Linkage Collaboration}\label{subsec:silc}


\subsection{Urban Big Data Centre}\label{subsec:ubdc}

Funding for this PhD was provided by the Scottish Government and the Economic \& Social Research Council (ESRC). The bid for funding was won by the Urban Big Data Centre (UBDC) which is based within the University of Glasgow. UBDC as an organisation is also funded by the ESRC and brings together data scientists and social scientists with research interests relevant to urban living such as; housing, transport, migration, and health [@RN472]. UBDC has six partner universities; Edinburgh, Bristol, Cambridge, Reading, Sheffield, and Illinois-Chicago. It is also one of three UK partner research institutions that share infrastructure facilities offered by SILC. 

The linkage project described in this thesis was completed with the assistance of UBDC's controlled data service which helps researchers to access personal data that exists in administrative databases [@RN475]. In addition to  a vigorous approval process, access to data is tightly controlled via safe haven IT architecture which monitors use of data and output of analyses to ensure individual anonymity is maintained [@RN475] (this process is more fully explained in sections \ref{sec:ig}). UBDC arranges acces to the safe haven environment though liaison with the electronic Data and Research Innovation Service (eDRIS), provided by the Information Services Division (ISD) of NHS National Services Scotland (NSS). 

\subsection{electronic Data and Research Innovation Service (eDRIS)}\label{subsec:edris}

ISD is a subdivision of NHS NSS [@RN324]. NSS is a national NHS Board in its own right and works with the other NHS Boards, particularly the 14 geographic health boards, to provide centralised services such as; procurement, legal support, IT, and public health intelligence [@RN473]. As a division of NSS, ISD provides, among other things, services and support for IT and public health intelligence [@RN324]. This includes administering the large number of databases containing information on health service use in Scotland varying from maternity \& births, to cancer sevices, and unscheduled health care [@RN324].


eDRIS is part of ISD and is detailed specifically with assisting research using health administrative datasets. Researchers using the eDRIS service have a named research assistant who provides advice on; data sources, study design, the information governance approvals system, access to the safe haven environoment, and review of analysis outputs to ensure disclosive information cannot be inferred [@RN324]. 

\subsection{Health and Social Care Analysis}\label{subsec:asd}

Health and Social Care Analysis (HSCA) is a division within the Socttish Government that provides statistic, economic, and research evidence to inform policy making in this area [@RN476]. It is one of many Analytical Service Divisions (ASD) that provide analytical support, advice, and briefing to the Government. HSCA creates reports and publications in a number of key areas including; social care, care homes, and mental health and is responsible for collecting and publishing the Social Care Survey (SCS) described in section \ref{sec:sources}

\subsection{National Records of Scotland}\label{subsec:nrs}

National Records of Scotland (NRS) collects and maintains information about the people of Scotland including births, deaths, and marriages [@RN477]. In addition to producing annual reports and population estimates, NRS provides a 

\section{Data Sources}\label{sec:sources}

[@RN352] Important to describe why and how data collected [@RN480]

\subsection{Social Care}\label{subsec:source-sc}

Descibe Social Care Survey

\subsection{Population Spine and Death records}

via eDRIS or direct NRS?? - demography and geography also.

\subsection{Prescribing Information System}

Describe PIS

\subsection{Unscheduled Care Data}

Describe USC data mart


\section{Information Governance}\label{sec:ig}

Use ADRN legal issues book
Also use SG priniciples for DL

\subsection{Research Approvals Commitee}\label{subsec:rac}

UBDC RAC process

\subsection{Public Benefit and Privacy Panel}\label{subsec:pbpp}

PBPP Process

\subsection{Ethics}\label{subsec:ethics}

College ethics and waivers

\subsection{Data sharing agreement}\label{subsec:dsa}

DSA description

\subsection{Safe Haven environment}\label{subsec:safe-haven}

describe safe haven

\section{Timeline}\label{sec:timeline}

Describe timeline of approvals process - major hurdles and barriers.