---
output: pdf_document
---

\chapter{Data Linkage, Information Governance, and Data Sources}\label{ch:data}

\section{Introduction}\label{sec:data-intro}

Intro to data linkage
IG inc infrastructure, approvals, processing, DSAs, and safe haven.
Data Sources descrip

\section{Data Linkage}\label{sec:data-linkage}

\epigraph{Record linkage refers to a merging that brings together information from two or more sources of data with the object of consolidating facts concerning an individual or an event that are not available in any separate record.}{\textit{[OECD, 2006]}}

Administrative data is data that is generated when individuals use a service of some description. Often in research terms, and exclusively in this thesis, administrative data refers to data generated by the use of \textit{public} services [@RN85; @RN352]. This data can describe the provision of a specific service or how it was administred by the provider [@RN85; @RN352]. As the above definition outlines, record linkage involves joining data about individuals from two or more administrative databases together [@RN279; @RN470] and is being increasingly used in social science research [@RN133; @RN276]. 

Using administrative data for research purposes has a number of advantages and disadvantages. The data is not collected for research purposes and as such may lack specific information relevant to a researcher's line of inquiry [@RN352]. This also reduces the ability of a study to adjust for all potential confounding variables, decreasing the ability to make causal inferences from the data [@RN352]. There is the potential for ambiguity about the coding of variables in a database and what each code represents [@RN352; @RN133; @RN398] which means specialist knowledge of the database and collection methods are required [@RN352]. Administrative databases also have the potential to contain data of questionable quality and high levels of missing data [@RN540; @RN480; @RN489]. Data can be missing for the same reasons as seen in other forms of research but, in addition, individuals may also be missing due to failure to interact with a service or because insufficient information was available to accurately match records during the data-linkage process [@RN489]. 

Advantages of administrative databases are that they enable large, often population sized, sample sizes because they are generated from service use [@RN352; @RN85; @RN398]. This characteristic also reduces the potential for sampling bias [@RN352]. Well maintained administrative data can offer information over long periods of time including very recent data [@RN85]. This can make inferences from research findings more robust with excellent levels of external validity without the extra cost traditional observational studies might incur [@RN352; @RN489]. The potential to link administrative databases from a number of sources is a significant advantage and offers insghts into how services interact [@RN352; @RN133; @RN398].

There are two main methods of linking data from disparate sources; deterministic matching and probabilistic matching [@RN279; @RN470; @RN491]. Where differing datasets possess common unique identifiers, determinsitic matching simply links data using this identifier. Probability matching methodology can be employed in the abscence of a common unique identifier [@RN279; @RN470; @RN491]. Using this method, a probability of two records matching correctly is calculated based on how well the records match based on a set of common partial identifiers such as name, date-of-birth, and postcode [@RN279; @RN470; @RN491]. An important consideration when using probabilistic linkage is making an assessment of false-positive match rates [@RN279; @RN470; @RN491]. There are three main strategies to assist with this assessment; measuring error using "gold-standard" data (such as a validated external datasets), sensitivity analyses (comparing results across differing linkage parameters), and comparing linked and unlinked data according to characteristics (such as sociodemographic subgroups) [@RN279]. 

Scotland is home to some of the best administrative databases in the world [@RN85]. This is particularly due to the high-quality of health datasets that have been collected and maintained for over 40 years [@RN85; @RN470]. Whilst linkage of differing health datasets has become common over this period, new cross-sectoral linkages are beginning to emerge such as health and educational data [@RN471], and health and social care data [@RN132]. These cross-sectoral linkages are providing new insights that have the potential to have lasting impact on policy and provision of services [@RN85; @RN133].   

\section{Information Governance}\label{sec:ig}

\subsection{Introduction}\label{subsec:ig-intro}

Confidentiality of data subjects is an important consideration in any data linkage project. The benefits of administrative data linkage outlined in section \ref{sec:-data-linkage} are dependent on research being conducted in a legally and ethically competent fashion. Whilst full anonymisation would be an effective way to protect data subjects confidentiality, it is almost impossible to achieve this with individual-level data suitable for research purposes [@RN489]. 

As an alternative, a process involving robust approvals review, researcher training with associated responsibilites and sanctions, and safe haven settings are used to preserve data subject confidentiality [@RN489].  This section outlines how this process was applied for the purposes of the data linkage completed in this thesis. Firstly, the various organisations that provide the infrastructure that enabled the data linkage to take place a briefly described. An overview of the various approvals and ethical panels is then provided, followed by the legal framework which enabled data processing to take place with a brief description of how confidentiality is maintained during the linkage process. 

\subsection{Infrastructure}\label{subsec:infrastructure}

\epigraph{The key test for an acronym is to ask whether it helps or hurts communication.}{\textit{Elon Musk}}

\subsubsection{Scottish Informatics and Linkage Collaboration}\label{subsec:silc}

The Scottish Informatics and Linkage Collaboration (SILC) is an umbrella term for a number of support services that are available to individuals wishing to conduct research using linked administrative data [@RN478]. Services include computing resources (provided by the University of Edinburgh), research and project coordination advice (provided by the electronic Data Research and Innovation Service (eDRIS)), and an indexing service (provided by the National Records of Scotland (NRS)) [@RN478]. SILC currently has three partner institutions; the Adminstrative Data Research Centres (ADRC), the Farr Institute, and the Urban Big Data Centre (UBDC) [@RN478].

\subsubsection{Urban Big Data Centre}\label{subsec:ubdc}

Funding for this PhD was provided by the Scottish Government and the Economic & Social Research Council (ESRC). The bid for funding was won by UBDC which is based within the University of Glasgow. UBDC as an organisation is also funded by the ESRC and brings together data scientists and social scientists with research interests relevant to urban living such as; housing, transport, migration, and health [@RN472]. UBDC has six partner universities; Edinburgh, Bristol, Cambridge, Reading, Sheffield, and Illinois-Chicago. 

The linkage project described in this thesis was completed with the assistance of UBDC's controlled data service. This service helps researchers to access personal data that exists in administrative databases [@RN475]. In addition to  a vigorous approval process, access to data is tightly controlled via safe haven IT architecture which monitors use of data and output of analyses to ensure individual anonymity is maintained [@RN475]. UBDC arranges acces to the safe haven environment though liaison with eDRIS, provided by the Information Services Division (ISD) of NHS National Services Scotland (NSS) under the auspices of SILC. A more detailed description of the safe haven is given in section \ref{subsec:safe-haven}. 

\subsubsection{electronic Data and Research Innovation Service}\label{subsec:edris}

ISD is a subdivision of NHS NSS [@RN324]. NSS is a national NHS board in its own right and works with the other NHS boards, particularly the 14 geographic health boards, to provide centralised services such as; procurement, legal support, IT, and public health intelligence [@RN473]. As a division of NSS, ISD provides, among other things, support for the latter two of these services [@RN324]. This includes administering the large number of databases containing information on health service use in Scotland varying from maternity & births, to cancer sevices, and unscheduled health care [@RN324].

eDRIS is part of ISD and provides services under SILC [@RN481]. It is detailed specifically with assisting research using health administrative datasets. Researchers using the eDRIS service have a named research assistant who provides advice on; data sources, study design, the information governance approvals system, access to the safe haven environoment, and review of analysis outputs to ensure disclosive information cannot be inferred [@RN324]. 

\subsubsection{National Records of Scotland}\label{subsec:nrs}

NRS collects and maintains information about the people of Scotland including births, deaths, and marriages [@RN477]. In addition to producing annual reports and population estimates, NRS provides the indexing service under SILC which enables anonymous linking of administrative databases as a TTP. 

\subsubsection{Health and Social Care Analysis}\label{subsec:asd}

Health and Social Care Analysis (HSCA) is a division within the Socttish Government that provides statistic, economic, and research evidence to inform policy making in this area [@RN476]. It is one of many Analytical Service Divisions (ASD) that provide analytical support, advice, and briefing to the Government. HSCA creates reports and publications in a number of key areas including; social care, care homes, and mental health and is responsible for collecting and publishing the Social Care Survey (SCS) described in section \ref{sec:sources}

\subsection{Approvals}\label{subsec:data-approvals}

As described in section \ref{subsec:ig-intro}, one of the ways in which data subject confidentiality is maintained in data linkage projects is through a rigorous and robust approvals process. Three seperate approvals were required for the purposes of data linkage in this thesis. 

\subsubsection{Research Approvals Commitee}\label{subsec:rac}

Data linkage for the project was facilitated by UBDC's controlled data service. In order to utilise this service, the data required for analyses required approval from the UBDC Research Approvals Committee (RAC). A full list of RAC members is available online [@RN475].  This committee is independent of UBDC and approves use of funds and infrastructure in UBDC and includes a lay member of the public [@RN475]. An application to use the controlled data service is judged on its academic merit, public benefit, skill of research team, and alignment with UBDC aims before being approved [@RN531]. 

The approval for the main linkage project is shown in Appendix C.

\subsubsection{Ethics}\label{subsec:ethics}

Ethical approval for data analysis was sought and gained from the University of Glasgow College of Social Sciences Research Ethics Committee (CoSS REC). A blanket ethical approval, obtained by eDRIS from the NHS East of Scotland REC, covers research that uses NHS Health data, does not involve direct contact with data subjects, has peer-review approval, stores data in the national safe haven, and is conducted by research teams based in the UK [@RN538]. The main linkage project therefore only required further approval from CoSS REC to cover the non-health related data (i.e. the Social Care Survey). 

The CoSS REC approval letter for the main linkage project is shown in appendix E. 

\subsubsection{Public Benefit and Privacy Panel for Health \& Social Care}\label{subsec:pbpp}

In addition to RAC and College ethical approval, the main thesis project also required clearance from the Public Benefit and Privacy Panel for Health & Social Care (PBPP). This was beacuse data from NHS sources were being used. The PBPP acts as a decision making body with delegated responsibility from NHS Scotland Chief Executive Officers and the Registrar General [@RN532]. Using terms of reference and guiding principles, the panel adjudicates whether research projects using administrative data generated by the NHS in Scotland can be used for research purposes. The panel ensures that the basis for disclosing data has a clear public benefit and ensures the legal basis for accessing and processing the data is sound. 

The approval letter for the main thesis project is shown in Appendix D, a fuller description data processing and the legal basis for this is presented in section \ref{subsec:dat-process}.


\subsection{Data processing}\label{subsec:dat-process}

\subsubsection{Legal framework}\label{subsec:dat-legal}

The permissions and linkage of data for this project were completed in advance of the European Union (EU) General Data Protection Regulation (GDPR) coming into effect in May 2018. The information governance was informed by antecendant laws including the Data Protection Act (DPA) (1998). However, as the study period was known to overlap with the implementaion of GDPR, all legal documentation was completed to ensure compliance with the incoming regulation.  

Data sharing and processing can be completed without consent of data subjects as long certain criteria, explicitly named in legislation, are met [@RN276].  For the purposes of this thesis, data processing was completed, without consent, in accordance with three legislative paragraphs:

\begin{itemize}[noitemsep]
\item Schedule 2:(6) of the DPA.
\begin{quotation} \begin{enumerate} \item The processing is necessary for the purposes of legitimate interests pursued by the data controller or by the third party or parties to whom the data are disclosed, except where the processing is unwarranted in any particular case by reason of prejudice to the rights and freedoms or legitimate interests of the data subject.\end{enumerate} \end{quotation}

\item Schedule 3:(8) of the DPA (emphasis added)
\begin{quotation} \begin{enumerate}
\item The processing is necessary for medical purposes and is undertaken by 
\begin{enumerate}
\item a health professional, or 
\item a person who in the circumstances owes a duty of confidentiality which is equivalent to that which would arise if that person were a health professional.
\end{enumerate}
\item In this paragraph “medical purposes” includes the purposes of preventative medicine, medical diagnosis, \emph{medical research}, the provision of care and treatment and the management of healthcare services
\end{enumerate}\end{quotation}

\item Paragraph 9 of the Data Protection (Processing of Personal Data Order 2000(SI 2000 No.417)).
\begin{quotation} The project has clear and substantial public interest in the information it will provide to inform the delivery of public services. The data processing is necessary to enable this research to take place. The project does not support measures of analysis with respect to any individual. Finally, the project will not cause any substantial damage or distress to any individual. \end{quotation}

\end{itemize}

Lawful processing of data for the purposes of the project is in accordance with a further two legal acts:- 

\begin{itemize}[noitemsep]
\item Social Work (Scotland) Act 1968.
\begin{quotation} 8 Research \begin{enumerate}
\item The Secretary of State may conduct or assist other persons in conducting research into any matter connected with his functions or the functions of local authorities in relation to social welfare, and with the activities of voluntary organisations connected with those functions.
\item Any local authority may conduct or assist other persons in conducting research into any matter connected with their functions in relation to social welfare.
\item The Secretary of State and any local authority may make financial assistance available in connection with any research which they may conduct or which they may assist other persons in conducting under the provisions of this section.
\end{enumerate} \end{quotation}
\item National Health Service (Scotland) Act 1978
\begin{quotation} 47 Education and research facilities. (2)Without prejudice to the general powers and duties conferred or imposed on the Secretary of State under the Scottish Board of Health Act 1919, the Secretary of State may conduct, or assist by grants or otherwise any person to conduct, research into any matters relating to the causation, prevention, diagnosis or treatment of illness, or into such other matters relating to the health service as he thinks fit."
\end{quotation}
\end{itemize}

Information governance for the project was also informed by the "Guiding Principles for Data Linkage" report produced by the Scottish Government [-@RN126]. These guidelines, themselves informed by legislation such as the DPA, highlight the importance of public interest, transparency, and privacy when conducting data linkage projects with publicly held data sets. 

In order to preserve anonymity whilst linking administrative data from different agencies, a method known as "linkage using a separation of functions" is employed [@RN279; @RN85]. This process involves the use of a Trusted Third Party (TTP) to process non-anonymised information in order to link more than one dataset together. The TTP receives personal information (e.g. names, addresses and dates-of-birth) from the data controllers of the adminstrative datasets to be used and creates index "keys" to send back to the data controllers to attach to their data [@RN279; @RN85]. The TTP creates a lookup table of index "keys" relevant to each dataset and sends these to a linkage agent. The linkage agent receives data from the data controllers \textit{without} personal information and links them together using the "keys" created by the TTP and makes this available to a researcher in a secure envirnonment [@RN279; @RN85]. This process means the TTP receives lots of personal information but no other information, the researcher has access to information relevant to their study but no personal information, and the data controllers share information about individuals in their datasets without compromising anonymity and without seeing data from each others databases [@RN479].

\subsubsection{Safe Haven environment}\label{subsec:safe-haven}


Another integral part of ensuring the confidentiality of data subjects within large, linked administrative data is by holding such data in a safe haven environment [@RN489]. As described in section \ref{subsec:ubdc}, access to data for this thesis was administered via UBDC's controlled data service and further liaison with eDRIS to enable use of the NSS National safe haven. All data shared for the purposes of the thesis was transferred by data controllers to the safe haven by secure file transfer protocol. 

The safe haven enables secure data storage and access via a Virtual Private Network (VPN) connection with strict access control. This environment does not enable external access of any kind i.e internet or saving & printing facilities [@RN529]. In order to retrieve output of analyses, work was submitted for statistical disclosure control which was conducted by eDRIS employees. This process ensures that data taken out of the safe haven cannot be used, either on its own or by being combined with other data, to breach the privacy of any individual [@RN529; @RN489]. A full guide to statistical disclosure control is provided by Lowthian & Ritchie [-@RN530]. 


\subsubsection{Data sharing agreement}\label{subsec:dsa}

For the purposes of the main linkage project, a three-way data sharing agreement (DSA) between the University of Glasgow, NHS National Services Scotland, and Scottish Ministers (Scottish Government) was signed. This detailed the purpose of data sharing, as well as the transfer, protection, and security of data. The  roles and responsibilites of each organisation in relation to relevant data protection legislation are clearly detailed in the DSA.  

\section{Data Sources for Linkage}\label{sec:sources}

\subsection{Introduction}\label{subsec:data-sources-intro}

Research conducted with administrative data requires a thorough description of databases used [@RN480]. This should include a description of the purpose of the data collection and the methods employed to collect data. This enables appraisal of any  potential biases that may exist within the databases [@RN352; @RN480]. There are 4 main sources of data used in the main analyses of this thesis: the Social Care Survey, the Scottish population spine and death records, the Prescribing Information System, and the Unscheduled Care Data Mart. Each of these are described in more detail below. 

Why collected? How collected? Data Quality checks?

\subsection{Social Care Survey}\label{subsec:source-sc}

The Social Care Survey (SCS) is collected annualy by HSCA for the Scottish Government to provide descriptive statistics of the amounts of social care delivered by each of Scotland's 32 local authorities [@RN487]. Results are collated and published annualy by HSCA in the "Social Care Services, Scotland" report [@RN487]. The SCS reports provide an overview of social care services for the public and policy makers. In addition, certain measures captured by the SCS are used in funding formulae to calculate allocation of resources to each local authority (e.g. number of people receiving home care) [@RN450]. 

All 32 Scottish local authorities collect information on social care as part of their management systems [@RN128]. HSCA produce a data specification document outlining the information that should be returned for the social care survey and this is sent to HSCA via a secure web-basesd system called ProcXed. This system supports data validation checks on transfer to improve data accuracy [@RN128]. 

The SCS has been collected in its present form since 2013 as a combination of two previous data collections - the Home Care Census and the Self Directed Support (Direct Payments) Survey [@RN128]. Individual-level data has been collected since 2010. Some questions have remained constant throughout this period but there have also been some changes in definitions and measures.

The most recent SCS (2017) collected information on on all indiviudals that received community alarm, telecare, self directed support (SDS) or social work/ support worker services during the previous financial year. In addition, individuals that received home care services, meals, housing support, shopping, or laundry services during a specified census week are included in the survey. 

Before 2013, information on telecare and community alarm services was only collected for individuals receiving these services during the census week. Furthermore, the value for total weekly hours of housing support services was included in the value of home care services. The separation of these services acknowledges that housing support is often regarded as 24-hour-a-day-7-day-a-week service [@RN128]. 

For the value of total weekly hours of home care, HSCA request details on scheduled and actual hours of care delivered. Some local authorities are able to return both values, others only return one value. Where both are returned, actual hours of home care are used in official reporting [@RN128]. Approximately 129,000 people received community alarms and/or telecare services, approximately 60,000 received home care services, and approximately 8,000 received SDS funding in 2016/17 [@RN128]. The overlap of individuals who receive more than one of these services is unknown. 

The cross-sectional nature of the survey, and in particular the census week variables, mean that the SCS only collects a sample of the entire population that receive social care in Scotland in any given financial year. It is unknown how large this sample is. It is also impossible to infer whether the values of total weekly hours of home care delivered to individuals is representative of the care they receive throughout the financial year. In order to gain a better understanding of these issues, an exploratory project, using a richer data set, was conducted as part of this thesis and is reported in chapter \ref{ch:renfrew}. 

\subsection{Population Spine and Death records}

**Need to add in source from NRS webpage**

The ‘Research population spine’ is a copy of the National Health Service Central Register (NHSCR) and is controlled by NRS. The spine contains over 9 million records and is updated quarterly. There are very strict policies which govern access to the offline secure server where the spine is stored. 

The NHSCR is used operationally for the purpose of transferring GP records.  Despite the name and the fact it is used for transferring patients records, the population spine does not hold medical records themselves. It contains records of anyone who was born in Scotland, who registers with a GP in Scotland, or who dies in Scotland. Variables included are: forename, middle name, surname, date of birth, gender, postcode, and country of birth. 

This resource is extremely useful for adminstrative data linkage projects. Data sources that don't contain a CHI number (such as the SCS) can be matched to the population spine using determinisitc and probabilistic methods (see section \ref{sec:data-linkage}). This then allows linkage to CHI-based data sources enabling cross-sectoral projects, such as the main analyses in this thesis, to be possible. 

\subsection{Prescribing Information System}

The Prescribing information system (PIS) contains all community prescribed medicines for every individual in Scotland from 2009 onwards. Data is collected to provide payment to community pharmacies for the medicines dispenced to the population. The data base can be linked to health sources via the Community Health Index (CHI) number. A full description of the PIS database and its applicability to research has been published by Alvarez-Madrazo et al [-@RN236]. 

\subsection{Urgent Care Data}

The Urgent Care Data Mart (UCD) is a database collated by ISD for the purpose of understanding a patient journey through emergency and urgent care services [@RN528]. It is a linkage of routine health data from a number of sources controlled by ISD: NHS24 telephone triage service, Scottish Ambulance Service (SAS), primary care out-of-hours services (PC OOH), Accident & Emergency (A & E), acute emergency inpatient admissions (both general and mental health), and deaths. Data is available from 2011 with the exception of PC OOH data which is available from 2014. CHI numbers are available on all records. 

Continous Urgent Care Pathways (CUPs) are calculated that join together records from each of these sources that occur within 24 hrs of each other (or for services occuring within 48hrs of an acute emergency admission)[@RN528]. Details of all variables listed in UCD are available in the background paper published by ISD [-@RN528]. In addition to service use, UCD flags presence of any of 14 long-term health conditions in any of the above datasets and, additionally, any acute admission from 1981 onwards.  


\section{Timeline}\label{sec:timeline}

Describe timeline of approvals process - major hurdles and barriers.


