---
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    latex_engine: xelatex
    dev: png
documentclass: report
classoption: a4paper,oneside,table
citecolor: blue #doesn't work
urlcolor: blue
linkcolor: blue
bibliography: references.bib
csl: harvard-cite-them-right.csl
fontsize: 12pt
geometry: top = 1.8cm, bottom = 1.8cm, left = 4cm, right = 1.5cm
header-includes:
- \usepackage{placeins} #FloatBarrier
- \usepackage{caption}
- \usepackage{fancyhdr} #for headers/footers
- \usepackage{setspace} #for 1.5 spacing
- \usepackage{chngcntr}
- \usepackage[export]{adjustbox}
- \usepackage{microtype}
- \usepackage{booktabs} #tables
- \usepackage{longtable}
- \usepackage{pdflscape}
- \usepackage{graphicx} #figures
- \usepackage{epigraph} #nice quotations
- \usepackage{pdfpages} #appendices
- \usepackage[inline]{enumitem} #no item seperate space
- \usepackage[flushleft]{threeparttable} #table footer 
- \usepackage[toc,page]{appendix} #appendix in toc
- \usepackage{acronym}
- \usepackage{float} # [H] argument for floats
- \usepackage[utf8]{inputenc} 
- \usepackage{xcolor}
- \usepackage{hyperref} #cross-refs and hyperlinks
- \onehalfspacing
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figures/', echo = FALSE,
                      warning = FALSE, message = FALSE)
knitr::opts_knit$set(base.dir = 'chapters/')
```


\pagenumbering{arabic}
\newpage
\pagestyle{fancy}

\fancyhf{}
\fancyhead[CE,CO]{\footnotesize \leftmark}
\fancyfoot[LE,LO]{\scriptsize \rightmark}
\fancyfoot[RE,RO]{\scriptsize Page \thepage}
\renewcommand{\headrulewidth}{0pt}


```{r child = '07_data.Rmd'}
```

#References