---
output: pdf_document
---

\chapter{Methods}\label{ch:methods}

\section{Information Governance}\label{sec:ig}

Use ADRN legal issues book
Also use SG priniciples for DL
Data linkage course material also. 

\subsection{Research Approvals Commitee}\label{subsec:rac}

UBDC RAC process

\subsection{Public Benefit and Privacy Panel}\label{subsec:pbpp}

PBPP Process

\subsection{Ethics}\label{subsec:ethics}

College ethics and waivers

\subsection{Data sharing agreement}\label{subsec:dsa}

DSA description

\subsection{Safe Haven environment}\label{subsec:safe-haven}

describe safe haven

\section{Timeline}\label{sec:timeline}

Describe timeline of approvals process - major hurdles and barriers.

\section{Cohort}\label{sec:cohort}

Describe the cohort - why it was chosen. How it was constructed

\section{Linkage process}\label{sec:linkage}

Detail of linkage process with diagramme. In-depth detail here. 

\section{Summary measures}\label{sec:summaries}

\subsection{Social Care Survey}\label{subsec:scs-summs}

Which variables were used and how summarised and cleaned (i.e. telecare as categorical etc.)

with reference to chapter \ref{ch:renfrew} and measure of hours of social care

\subsection{Prescribing Information Service}\label{subsec:pis-summs}

How PIS data was summarised and measures chosen

\subsection{Demographic, geographic, and deaths information}\label{subsec:nrs-summs}

Which Local Authority? Which SIMD data?

\subsection{Unscheduled care measures}\label{subsec:usc-summs}

How was usc data wrangled? Which summary measures were chosen?

\section{Statistical methods}

Which summary and model statisitics were used to answer research questions. 
